breatheco-de/app

.github/workflows/cypress.yml, cypress.json, cypress/fixtures/example.json, cypress/integration/example/index.spec.js, cypress/plugins/index.js, cypress/support/commands.js, cypress/support/index.js, package-lock.json, package.json
>PR created for issue [#1638](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/1638)
=> initializing cypress

package-lock.json, src/common/components/CallToAction.jsx, src/common/components/CohortSideBar.jsx, src/common/components/Icon/set/arrowLeft.jsx, src/common/components/ModuleMap.jsx, src/common/components/Navbar.jsx, src/common/components/SupportSidebar.jsx, src/common/utils/iconDict.json, src/common/utils/mockData/DashboardView.js, src/stories/CallToAction.stories.jsx, src/stories/CohortSideBar.stories.jsx, src/stories/DashBoardView.stories.jsx, src/stories/ModuleMap.stories.jsx, src/stories/Navbar.stories.jsx, src/stories/SupportSidebar.stories.jsx
> PR created for issue [#1742](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/1742)
=> call to action component implemented

src/common/components/AttendanceModal.jsx, src/common/components/Heading.jsx, src/common/components/Icon/set/arrowRight.jsx, src/common/components/Icon/set/checked.jsx, src/common/components/Icon/set/longArrowRight.jsx, src/common/components/Text.jsx, src/common/components/Timeline.jsx, src/common/utils/iconDict.json, src/common/views/Dashboard.jsx, src/stories/AttendanceModal.stories.jsx, src/stories/Heading.stories.jsx, src/stories/Text.stories.jsx, src/stories/Timeline.stories.jsx
> PR created for issues [#1696](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/1696) and [#1698](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/1698)
=> Attendance Modal and Timeline components to be reviewed

src/pages/interactive-coding-tutorial/[difficulty]/[slug].jsx, src/pages/interactive-exercises/[slug].jsx
> PR created for issue [#1955](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/1955)
=> updated markdown skeleton loader

package.json, src/common/components/Choose.jsx, src/common/components/MDSkeleton.jsx, src/common/components/MarkDownParser/Anchor.jsx, src/common/components/MarkDownParser/index.jsx, src/common/components/MarkDownParser/markdown.js, src/common/components/MarkDownParser/toc.jsx, src/pages/cohort/[cohortSlug]/[slug]/[version]/index.jsx, src/pages/lesson/[slug].jsx, src/pages/lessons.jsx, styles/globals.css
>- [Finish Lessons Page (and single page) (BC APP) #1938](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/1938)
>- [Module Map component and integration with backend #1953](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/1953)
=> Finished Lesson page content details

.eslintrc.js, package.json, scripts/_utils.js, scripts/make.iconDict.js, src/common/components/FilterModal/difficulty.jsx, src/common/components/FilterModal/technologies.jsx, src/common/components/Forms/actions.js, src/common/components/Forms/validationSchemas.js, src/common/components/MDSkeleton.jsx, src/common/components/MarkDownParser/Anchor.jsx, src/common/components/MarkDownParser/index.jsx, src/common/components/MarkDownParser/markdown.js, src/common/components/MarkDownParser/toc.jsx, src/common/utils/leads.js, src/js_modules/navbar/DesktopNav.jsx, src/js_modules/navbar/MobileNavItem.jsx, src/js_modules/projects/ProjectList.jsx, src/js_modules/projects/Search.jsx, src/pages/about-us.jsx, src/pages/interactive-coding-tutorial/[difficulty]/[slug].jsx, src/pages/interactive-exercises/[slug].jsx, src/pages/interactive-exercises/index.jsx, src/pages/lesson/[slug].jsx, src/pages/lessons.jsx, src/pages/projects.jsx, src/utils/url.js, styles/globals.css
PR created for issues:
>- [About-US section should load from different markdown #2075](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/2075)
>- [Project/Exercises checkbox filters should be OR instead of AND #2074](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/2074)
>- [Upgrades to the single exercisen and single project view #2076
](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/2076)
>- [x]  Dark mode buggy, some colors are not properly set, for example: [https://app-git-fork-arielcalisaya-fix-friday7-breathecode.vercel.app/lessons?child=1](https://app-git-fork-arielcalisaya-fix-friday7-breathecode.vercel.app/lessons?child=1)
>- [x]  On the `/lessons` if one day comes without any activities (lessons, etc) don't include it on the list.
>- [x] …
=> Big Fixes and page improvements

src/common/components/Choose.jsx, src/common/components/Navbar/Session-2.jsx, src/common/components/SupportSidebar.jsx, src/common/context/AuthContext.jsx, src/common/hooks/useModuleHandler.js, src/common/translations/dashboard.js, src/common/views/Dashboard.jsx, src/js_modules/moduleMap/module.jsx, src/js_modules/moduleMap/taskHandler.bak.jsx, src/js_modules/moduleMap/taskHandler.jsx, src/pages/choose-program.jsx, src/pages/cohort/[cohortSlug]/[slug]/[version]/index.jsx
- Removed popover menu when click on taskIcon
- Fast change when click on taskIcon
- Reduced code lines
- Reused components
- Created localStorage item called `cohortSession`
- Way to use i18n without getStaticProps or getServerSideProps
- Created example of list of translation for dashboard in `src/common/translations/dashboard.js`
=> HOTFIX: Improvements on taskHandler!

package-lock.json, package.json, src/common/components/MarkDownParser/ContentHeading.jsx, src/common/components/MarkDownParser/index.jsx, src/common/components/MarkDownParser/syntaxHighlighter/tomorrow.js, src/common/components/MarkDownParser/toc.jsx, src/common/components/Timeline.jsx, src/js_modules/moduleMap/taskHandler.jsx, src/js_modules/navbar/MobileNav.jsx, src/pages/syllabus/[cohortSlug]/lesson/[lessonSlug]/index.jsx, styles/globals.css
- fixed  Quiz iframe re-render when state changes
- [decode emojis from binary](https://github.com/breatheco-de/app/pull/117/commits/f3c4298b028e115effbb22fc0b85c621fd2a258d)
- updated css for markdown-body properties
- emoji shortcodes (`:+1:` = :+1: )
=> 🐞 Minor bug Fixes (working...)

.env.example, src/common/components/Loading.jsx, src/pages/_app.jsx, src/pages/read/[slug].jsx
>PR created for issue [Move Loadbar above of the navbar #2258](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/2258)
=> Loader component fixed to screen

src/common/components/CallToAction.jsx, src/js_modules/chooseProgram/index.jsx, src/js_modules/moduleMap/index.jsx, src/pages/cohort/[cohortSlug]/[slug]/[version]/index.jsx, src/utils/index.js
>- [Start todays module not scrolling properlly #2222](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/2222)
>- [4Geeks - Select Program - Ajuste de Estilos y Programas Finalizados #2274](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/2274#event-6140030715)
=> hotfix 01-03-2022

src/js_modules/moduleMap/index.jsx, src/pages/cohort/[cohortSlug]/[slug]/[version]/index.jsx, src/pages/lesson/[slug].jsx, src/pages/syllabus/[cohortSlug]/[lesson]/[lessonSlug]/index.jsx, src/utils/markdown.js, styles/markdown.css
>PR created for issue:
>- [Asset URL's images are broken on the public pages, not inside the private ones #2347](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/2347)
>- [4Geeks Academy - Module Remain #2277](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/2277)
=> updates in lesson page and dashboard modules

package-lock.json, package.json, src/common/components/BeforeAfterSlider.jsx, src/common/components/Icon/set/youtube.jsx, src/common/components/MarkDownParser/index.jsx, src/common/components/ReactPlayer/index.jsx, src/common/components/StickySideBar.jsx, src/pages/example.jsx, src/pages/syllabus/[cohortSlug]/[lesson]/[lessonSlug]/index.jsx, styles/markdown.css
>PR created for issue [Assets with videos #2396](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/2396)
>- Improvement on markdown css (tables)
>- fixed heading on markdown
>- Video tutorial button on sticky sidebar
>- ReactPlayer component
>- Fixed re-rendering issue in scrollToTop function
=> video tutorial button

i18n.js, next.config.js, src/common/components/Navbar/index.jsx, src/lib/redirectsHandler.js, src/pages/_app.jsx, src/pages/_middleware.js, src/pages/cohort/[cohortSlug]/[slug]/[version]/index.jsx, src/pages/lesson/[slug].jsx, src/pages/lesson/_middleware.js
>PR linked with issue ["On the private and public lesson page, the lesson should be loaded based on the session language #2268"](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/2268)
=> Improvements in `/lesson/<slug>` page for page translations and smart `locale/lang` redirects

i18n.js, src/pages/_middleware.js, src/pages/lesson/_middleware.js
>PR created linked with issue [On the private and public lesson page, the lesson should be loaded based on the session language #2268](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/2268)
=> Logic for redirects with locale and language for lessons

src/common/context/AuthContext.jsx, src/pages/_app.jsx, src/pages/choose-program/_middleware.js, src/pages/cohort/[cohortSlug]/[slug]/[version]/index.jsx
>PR linked with issue [If I go to "choose program" without being logged in, it should redirect to the login view #2508](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/2508)
=> redirect for choose-program

public/locales/en/syllabus.json, public/locales/es/syllabus.json, src/common/components/Icon/set/google-collab.jsx, src/js_modules/navbar/DesktopNav.jsx, src/pages/interactive-coding-tutorial/[difficulty]/[slug].jsx, src/pages/interactive-exercises/[slug]/index.jsx, src/pages/syllabus/[cohortSlug]/[lesson]/[lessonSlug]/index.jsx, styles/markdown.css, styles/theme.js
>PR linked with issue [https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/2529](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/2529)
=> responsive improvement for code and exercises page and open in google collab link for ipynb lessons

src/pages/about-us.jsx
>PR created for issue [Fixes to /about-us section #2556](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/2556)
=> Updated about-us page

src/common/components/OnlyFor.jsx, src/common/services/breathecode.js, src/pages/cohort/[cohortSlug]/[slug]/[version]/index.jsx, src/pages/example.jsx
>PR created for issue [[future] Component to show or hide functionalities according to the role and academy #2446](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/2446)
=> Updated OnlyFor component

public/locales/en/syllabus.json, public/locales/es/syllabus.json, src/common/components/CallToAction.jsx, src/common/components/MarkDownParser/ContentHeading.jsx, src/common/components/MarkDownParser/index.jsx, src/common/components/Timeline.jsx, src/pages/syllabus/[cohortSlug]/[lesson]/[lessonSlug]/index.jsx
>PR created for issue [4Geeks - Hover y Selección de Lección #2486](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/2486)
=> Updated css style in timeline and translation for learnpack callToAction

src/common/components/Helmet.jsx, src/pages/_app.jsx, src/pages/_middleware.js
>PR linked with issue [Integracion con stonlyTrack #2564](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/2564)
=> updated stonly track

src/common/components/MarkDownParser/ContentHeading.jsx, src/common/components/MarkDownParser/index.jsx, src/pages/syllabus/[cohortSlug]/[lesson]/[lessonSlug]/index.jsx
>PR linked with issue [4Geeks - "Edit on Github" link #2575](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/2575)
=> updated edit markdown and ipynb links

package-lock.json, package.json, src/common/context/AuthContext.jsx, src/common/services/breathecode.js
>[Implement SWR hook for AuthContext.jsx file (BC App) #2063](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/2063)
>[Dashboard dont show courses and its in blank 🔥 💥 💥 💥 💣 : #2626](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/2626)
>[If the token expires 4geeks.com should take me to login #2596](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/2596)
=> Integration SWR hook for token real time handling

i18n.js, package.json, public/locales/en/common.json, public/locales/es/common.json, src/js_modules/projects/SimpleTable.jsx, src/pages/_middleware.js, src/pages/project/[slug].jsx, src/pages/project/_middleware.js
>PR created for issue [New redirect for projects #2620](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/2620)
=> new pathname for `/projects/slug` pages

src/common/hooks/useModuleHandler.js, src/js_modules/moduleMap/modalInfo.jsx, src/js_modules/moduleMap/taskHandler.jsx
>PR created for issue ["remove delivery" button not working on assignments #2627](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/2627)
=> change `revision_status` to pending

public/locales/en/common.json, public/locales/en/syllabus.json, public/locales/es/common.json, public/locales/es/syllabus.json, src/common/components/Icon/set/arrowLeft2.jsx, src/common/components/Icon/set/checked2.jsx, src/common/components/Icon/set/close.jsx, src/common/components/Icon/set/unchecked.jsx, src/js_modules/moduleMap/taskHandler.jsx, src/pages/syllabus/[cohortSlug]/[lesson]/[lessonSlug]/index.jsx, src/utils/index.js, styles/globals.css, styles/markdown.css
>PR linked with issue[Button to "mark as read" a lesson after scrolling down #2439](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/2439)
=> Syllabus page update: +Button mark as read, +Prev and Next button and +Modal warn

src/pages/interactive-exercises/index.jsx, src/pages/projects.jsx
>PR created for issue [Why are there exercises in both languages? #2672](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/2672)
=> Filter list of projects and exercise by current language

public/locales/en/dashboard.json, public/locales/es/dashboard.json
>PR created for issue [Stop redirecting to public-support-full-stack, only redirect to academy slack in general. #2669](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/2669)
=> updated slack link

src/common/components/Helmet.jsx
>PR created for issue [Traducción Hreflang's para SEO #2680](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/2680)
=> tag hrefLang

src/common/components/AttendanceModal.jsx, src/pages/cohort/[cohortSlug]/[slug]/[version]/index.jsx, src/pages/syllabus/[cohortSlug]/[lesson]/[lessonSlug]/index.jsx
>PR linked with issues
>- [Sort the attendancy list by name and last name #2684](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/2684)
>- [Video solution now showing up #2686](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/2686)
=> sorted student list and fixed disabled solution video button

public/locales/en/alert-message.json, public/locales/en/common.json, public/locales/en/profile.json, public/locales/es/alert-message.json, public/locales/es/common.json, public/locales/es/profile.json, src/common/components/Icon/set/certificate.jsx, src/common/context/AuthContext.jsx, src/common/services/breathecode.js, src/lib/redirectsHandler.js, src/pages/how-to/[slug]/_middleware.js, src/pages/interactive-coding-tutorial/[difficulty]/_middleware.js, src/pages/interactive-exercises/[slug]/_middleware.js, src/pages/lesson/_middleware.js, src/pages/profile/index.jsx, src/pages/profile/profileForm.jsx, src/pages/project/_middleware.js, styles/components/customLink.js, styles/theme.js
>PR created for isses
>- [Alias redirection not working on public pages #2707](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/2707)
>- [Add redirect from API /registry/alias/redirects #2724](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/2724)
>- [4Geeks - My Profile (Edición de Data y Certificados) #2043](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/2043)
>- [Disconnect github account #2664](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/2664)
=> Integration of alias endpoint, redirects and unlink github account

src/common/components/Helmet.jsx, src/pages/about-us.jsx, src/pages/how-to/[slug]/index.jsx, src/pages/how-to/index.jsx, src/pages/interactive-coding-tutorial/[difficulty]/[slug].jsx, src/pages/interactive-exercises/[slug]/index.jsx, src/pages/interactive-exercises/index.jsx, src/pages/lesson/[slug].jsx, src/pages/login/index.jsx, src/pages/project/[slug].jsx, src/pages/projects.jsx, src/pages/read/[slug].jsx
>PR created for hrefLang issue
>- Missing self-referencing link
>- Missing x-default
>- Some pages are not canonical
=> seo fixes for canonical url in og:url tag

i18n.js, next.config.js, public/locales/en/exercises.json, public/locales/en/lesson.json, public/locales/es/exercises.json, public/locales/es/lesson.json, public/robot.txt, src/common/components/FilterModal/difficulty.jsx, src/common/components/FilterModal/index.jsx, src/common/components/FilterModal/technologies.jsx, src/common/components/TagCapsule.jsx, src/js_modules/projects/ProjectList.jsx, src/js_modules/projects/Search.jsx, src/js_modules/projects/SimpleTable.jsx, src/js_modules/projects/TitleContent.jsx, src/pages/how-to/[slug]/index.jsx, src/pages/how-to/index.jsx, src/pages/interactive-coding-tutorial/[difficulty]/[slug].jsx, src/pages/interactive-exercise/[slug]/index.jsx, src/pages/interactive-exercises.jsx, src/pages/lesson/[slug].jsx, src/pages/lesson/_middleware.js, src/pages/lesson/index.jsx, src/pages/lessons.jsx, src/pages/project/[slug].jsx, src/pages/projects.jsx, src/pages/read/[slug].jsx
>PR created for issue [SEO Changes #2804](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/2804)
=> code improvements and lessons page

scripts/sitemap-generator.js, src/common/components/NextChakraLink.jsx, src/pages/login/index.jsx, styles/globals.css
>PR created for issue [Sitemap change frequency #2871](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/2871)
=> updated frequently change for sitemap

scripts/sitemap-generator.js, src/common/components/FilterModal/difficulty.jsx, src/common/components/FilterModal/index.jsx, src/js_modules/projects/ProjectList.jsx, src/pages/how-to/index.jsx, src/pages/interactive-coding-tutorial/index.jsx, src/pages/interactive-exercises.jsx, src/pages/lessons.jsx
>PR created for issue [When lesson, exercies or projects filters change, the url must be updated #2868](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/2868)
=> updated filterModal with queryString

src/common/context/AuthContext.jsx, src/pages/login/index.jsx
>PR created for issue [Grab session from querystring token #2865](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/2865)
=> redirect to last private page redirected for github login

package-lock.json, package.json, public/locales/en/alert-message.json, public/locales/en/common.json, public/locales/es/alert-message.json, public/locales/es/common.json, src/common/components/ReactSelect.jsx, src/js_modules/assignmentHandler/index.jsx, src/pages/cohort/[cohortSlug]/[slug]/[version]/assignments.jsx
>PR created for issue [New assignments module #2670](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/2670)
=> Updated selector with input and filters with querystring

src/common/components/AttendanceModal.jsx, src/common/components/InterceptionLoader.jsx, src/common/components/TeacherSidebar.jsx, src/common/context/AuthContext.jsx, src/common/context/PrivateRouteWrapper.jsx, src/js_modules/assignmentHandler/index.jsx, src/pages/_app.jsx, src/pages/choose-program/index.jsx, src/pages/cohort/[cohortSlug]/[slug]/[version]/assignments.jsx, src/pages/cohort/[cohortSlug]/[slug]/[version]/index.jsx
>PR created for issue [Intercept requests for 401 to logout the user #2869](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/2869)
=> logout for interceptions with status 401

package-lock.json, package.json, public/locales/en/syllabus.json, public/locales/es/syllabus.json, src/common/components/ShareButton.jsx, src/js_modules/moduleMap/taskHandler.jsx, src/pages/syllabus/[cohortSlug]/[lesson]/[lessonSlug]/index.jsx, src/utils/index.js, styles/components/customButton.js, styles/markdown.css
>PR created for issue [share on twitter or linkedin button #2736](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/2736)
=> share button for syllabus page

public/locales/en/alert-message.json, public/locales/es/alert-message.json, src/common/components/Forms/Register.jsx, src/common/components/profileForm.jsx, src/common/components/taskLabel.jsx, src/common/services/breathecode.js, src/js_modules/assignmentHandler/index.jsx, src/js_modules/navbar/MobileItem.jsx, src/pages/choose-program/index.jsx, src/pages/cohort/[cohortSlug]/[slug]/[version]/assignments.jsx, src/pages/index.jsx, src/pages/login/index.jsx, src/pages/thank-you.jsx, src/utils/index.js
>PR created for issues
- [Small changes to assignmets view #2923](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/2923)
- [New assignments module #2670](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/2670)
- [Grab session from querystring token #2865](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/2865)
=> updated assignments page and removed cookies storage

src/lib/redirectsHandler.js, src/pages/lesson/[slug].jsx
>PR created for issue [Lesson Doesn't Load in Spanish #2936](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/2936)
=> fix lesson language redirect

src/common/components/CohortSideBar.jsx, src/common/components/Forms/LogIn.jsx, src/common/services/breathecode.js, src/js_modules/navbar/MobileNav.jsx, src/pages/cohort/[cohortSlug]/[slug]/[version]/index.jsx, src/pages/index.jsx
>PR created for issue [The content of page is empty if I go from this url #2960](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/2960)
=> Fixed Application error

src/js_modules/projects/ProjectList.jsx
>PR created for issue [New landing page for tecnologies #2926](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/2926)
=> fixed template columns

public/locales/en/assignments.json, public/locales/es/assignments.json, src/pages/cohort/[cohortSlug]/[slug]/[version]/assignments.jsx
>PR created for issue [Display total number of assignments #3003](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/3003)
=> Display total number of assignments

src/common/hooks/useDebounce.js, src/js_modules/projects/Search.jsx, src/pages/how-to/index.jsx, src/pages/interactive-coding-tutorials/index.jsx, src/pages/interactive-exercises/index.jsx, src/pages/lessons/index.jsx
>PR created for issue [Search bar must search on the backend #3019](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/3019)
=> updated search list

src/common/components/Timeline.jsx, src/js_modules/moduleMap/module.jsx, src/pages/cohort/[cohortSlug]/[slug]/[version]/index.jsx, src/pages/syllabus/[cohortSlug]/[lesson]/[lessonSlug]/index.jsx
>PR created for issue [Include a warning on cohort dashboard about pending projects #2567](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/2567)
=> updated function to isMandatoryTimeOut

public/locales/en/dashboard.json, public/locales/en/navbar.json, public/locales/es/dashboard.json, public/locales/es/navbar.json, src/common/components/Navbar/index.jsx, src/common/components/SupportSidebar/Mentoring.jsx
>PR linked with issues
>- [Comment "Social & Live Learning" menu until we have the backend and the rest of the features ready. #3067](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/3067)
>- [Component: Dont Get Stuck v2.0 #3031](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/3031)
=> coment unused changes for now

public/locales/en/common.json, public/locales/en/dashboard.json, public/locales/es/common.json, public/locales/es/dashboard.json, src/common/components/Module.jsx, src/common/components/SupportSidebar/Mentoring.jsx, src/js_modules/moduleMap/modalInfo.jsx, src/js_modules/moduleMap/module.jsx
>PR created for issue [Open assets.target="blank" in a new window #3064](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/3064)
=> link condifitonal with target prop

public/locales/en/exercises.json, public/locales/es/exercises.json, src/pages/interactive-exercise/[slug]/index.jsx
https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/3030
=> add url to how to clone

src/common/components/Timeline.jsx, src/js_modules/moduleMap/modalInfo.jsx, src/pages/syllabus/[cohortSlug]/[lesson]/[lessonSlug]/index.jsx
>PR created for issue [On the syllabus sidebar, the tarket=blank tasks should open in a new window #3104](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/3104)
=> conditional for target blank in syllabus pages

src/stories/AlertMessage.stories.jsx
https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/3034
=> add AlertMessage to storybook

src/pages/profile/[slug].jsx
>PR linked with [Make the modal for uplding the image a lot smaller (like half).](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/2767#issuecomment-1224885609)
=> resized modal

src/common/components/AttendanceModal.jsx
>PR linked with issue [Bug en las asistencias #3118](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/3118)
=> fixed day as string issue

public/locales/en/dashboard.json, public/locales/es/dashboard.json, src/common/components/AttendanceModal.jsx, src/js_modules/moduleMap/modalInfo.jsx, src/pages/cohort/[cohortSlug]/[slug]/[version]/index.jsx, src/pages/read/[slug].jsx
>PR created for issue [Warn user about number of days when taking attendancy #3146](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/3146)
=> warn for attendance modules

src/common/components/MarkDownParser/index.jsx, src/common/components/ReactPlayerV2.jsx, src/pages/syllabus/[cohortSlug]/[lesson]/[lessonSlug]/index.jsx, styles/globals.css
>PR created for issue ([Loom videos not loading on projects inside 4geeks.com #3149](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/3149))
=> loom videos

src/common/components/ShareButton.jsx, src/common/components/Timeline.jsx, src/js_modules/moduleMap/module.jsx, src/pages/syllabus/[cohortSlug]/[lesson]/[lessonSlug]/index.jsx
>PR created for issue [Sharing your progress when delivering a CUSTOM project contains a broken link. #3096](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/3096)
=> fixed link in share component

public/locales/en/mentorship.json, public/locales/es/mentorship.json, src/common/components/Icon/set/regularFace.jsx, src/common/components/Icon/set/sad.jsx, src/pages/mentorship/index.jsx
https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/2574
=> changes to mentorship view

src/common/hooks/useModuleHandler.js, src/js_modules/moduleMap/index.jsx
>PR created for issue [Error when synchinizing changes on the syllabus #3220](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/3220)
=> fix sync module

public/locales/en/common.json, public/locales/en/learn-to-code.json, public/locales/es/common.json, public/locales/es/learn-to-code.json, src/common/components/ScrollSpy.jsx, src/common/components/Text.jsx, src/js_modules/landing/events.jsx, src/js_modules/landing/mentors.jsx, src/js_modules/landing/previewModules.jsx, src/js_modules/landing/pricing.jsx, src/pages/learn-to-code/index.jsx, styles/globals.css
>PR created for issue [Landing Page for Coding Introduction course #3154](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/3154)
=> Landing Updates

src/common/components/CohortSideBar.jsx, src/common/context/ConnectionContext.jsx, src/common/hooks/useConnect.js, src/common/hooks/useOnline.js, src/pages/_app.jsx
>PR linked with issue [Socket connection to retrieve online status on avatar component #3065](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/3065)
=> useOnline hook

public/locales/en/common.json, public/locales/es/common.json, src/common/components/MarkDownParser/SubTasks.jsx, src/common/components/MarkDownParser/index.jsx, src/common/components/ProgressCircle/Counter.jsx, src/common/components/ProgressCircle/index.jsx, src/common/components/Timeline.jsx, src/common/hooks/useInterval.js, src/common/services/breathecode.js, src/js_modules/syllabus/getReadme.jsx, src/pages/syllabus/[cohortSlug]/[lesson]/[lessonSlug]/index.jsx, src/stories/SubTasks.stories.jsx, styles/markdown.css
>PR created for issue [Improve MarkdownReader with Checkbox Tasks feature #3147](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/3147)
=> SubTasks component

public/locales/en/dashboard.json, public/locales/es/dashboard.json, src/common/components/AttendanceModal.jsx, src/common/components/OnlyFor.jsx, styles/components/customButton.js
>PR created for issue [Warn teacher about number of days when taking attendancy #3146](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/3146)
=> warn teacher about number of duration_in_days

src/common/components/CohortSideBar.jsx, src/common/components/MarkDownParser/MDComponents/index.jsx
>PR created for issue [Ability to nest checkboxes on MarkdownParser #3495](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/3495)
=> Checkbox child

src/common/components/MarkDownParser/index.jsx, src/pages/interactive-coding-tutorial/[difficulty]/[slug].jsx, src/pages/project/[slug].jsx, styles/markdown.css
>- [Code highlighting its loosing format #3523](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/3523)
>- [MarkdownParser: Error interpretando coding inline #3524](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/3524)
>- [Fix images on MarkdownParser #3522](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/3522)
=> Fix issue with format mistake in Markdown

i18n.js, public/locales/en/how-to.json, public/locales/es/how-to.json, src/common/components/CohortSideBar.jsx, src/common/components/Footer.jsx, src/common/components/GridContainer.jsx, src/common/components/useOnScreen.jsx, src/pages/how-to/technology/[technology].jsx, src/pages/interactive-coding-tutorial/[difficulty]/[slug].jsx, src/pages/lesson/[slug].jsx, styles/markdown.css
>- [What happned with pagination #3541](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/3541)
>- [Landing de how'to por tecnologia esta roto #3557](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/3557)
>- [Layout de jupyter notebooks esta completamente roto #3556](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/3556)
=> show and hide buttons and removed popover

src/pages/interactive-exercise/[slug]/index.jsx, styles/components/customButton.js
>PR created for issue [Intercambiar botones para acceder a los ejercicios. #3555](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/3555)
=> updated button

public/locales/en/social.json, public/locales/es/social.json, src/common/components/Footer.jsx, src/common/hooks/useModuleHandler.js, src/js_modules/syllabus/dataFetch.jsx, src/utils/index.js
=> Revert "Social media links changed "

src/common/components/MarkDownParser/MDComponents/index.jsx, src/js_modules/moduleMap/taskHandler.jsx
>PR linked with issue [Espaciado extraño en deliver assignment #3584](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/3584)
=> markdown anchor style fixes

src/common/components/Module.jsx
>PR created for issue [Tabs are not opening #3585](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/3585)
=> Fix onClick bug

src/common/components/NextChakraLink.jsx, src/pages/read/[slug].jsx, styles/globals.css
>- [Al darle click a Read and Watch en el footer, se mantiene al final de la pagina #3596](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/3596)
>- [The search bar should look for the lessons instead of sections #3597](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/3597)
=> changed scroll, to top

src/common/components/AttendanceModal/AttendanceTable.jsx, src/common/components/AttendanceModal/index.jsx, src/common/services/breathecode.js
>PR created for issue [replace the service used to take attendance#3508](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/3508)
=> Replace service to take attendance

public/locales/es/how-to.json, src/pages/how-to/[slug]/index.jsx, src/pages/how-to/index.jsx, src/pages/how-to/technology/[technology].jsx
>PR created for issue [In the how-to landing it's showing all the articles instead of only the how-to#3619](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/3619)
=> Filter results by category how-to

package-lock.json, src/common/components/ProgramCard.jsx
https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/3616
=> Program card

src/common/services/breathecode.js, src/js_modules/assignmentHandler/PopoverHandler.jsx, src/js_modules/moduleMap/module.jsx, src/js_modules/moduleMap/taskHandler.jsx, src/pages/cohort/[cohortSlug]/[slug]/[version]/assignments.jsx, src/pages/interactive-exercise/[slug]/index.jsx, src/pages/syllabus/[cohortSlug]/[lesson]/[lessonSlug]/index.jsx
>PR created for issue [Add academy_id to the header when asking for task attachments #3697](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/3697)
=> Academy header

public/locales/en/alert-message.json, public/locales/es/alert-message.json, src/common/components/AttendanceModal.jsx, src/common/components/TeacherSidebar.jsx, src/common/hooks/useCohortHandler.js, src/pages/cohort/[cohortSlug]/[slug]/[version]/assignments.jsx, src/pages/cohort/[cohortSlug]/[slug]/[version]/index.jsx
>- [Only students should show on the list of delivered assignments#3679](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/3679)
>- [Bug en la modal de asistencia cuando la tomas en dos cohorts diferentes. #3702
](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/3702)
=> fix error message when fetch students fails and modal bug

src/common/components/KPI.jsx, src/stories/KPI.stories.jsx, src/stories/KPIChart.stories.jsx
>PR linked with issue [The label should be optional in the KPIs component #3684](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/3684)
=> fontSize KPI

public/locales/en/common.json, public/locales/en/dashboard.json, public/locales/es/common.json, public/locales/es/dashboard.json, src/common/components/AttendanceModal/index.jsx, src/pages/cohort/[cohortSlug]/attendance.jsx
>PR created for issue [Warn teacher about number of days when taking attendancy #3146](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/3146#top)
=> show warning of attendance list

src/common/services/breathecode.js
=> bc_token queryString env

src/common/components/AttendanceModal/index.jsx
>PR created for issue [Warn teacher about number of days when taking attendancy #3146](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/3146)
=> fix warn function in attendanceModal

src/js_modules/moduleMap/module.jsx, src/js_modules/moduleMap/taskHandler.jsx, src/pages/syllabus/[cohortSlug]/[lesson]/[lessonSlug]/index.jsx
>- [Spanglish on 4Geeks.com #3723](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/3723)
>- [El frontend no está mostrando la duración en días correcta para cada módulo #3817](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/3817)
=> translation for popover description and fix for duration_in_days

src/common/components/MarkDownParser/MDComponents/index.jsx
>PR created for issue [Mala generacion de los substasks en el MarkdownReader #3828](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/3828)
=> Improved text recopilation of checkbox tag

public/locales/en/dashboard.json, public/locales/es/dashboard.json, src/common/components/AttendanceModal/index.jsx
>PR linked with issue [Warn teacher about number of days when taking attendancy#3146](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/3146)
=> fix alert message

src/pages/cohort/[cohortSlug]/attendance.jsx
>PR created for issue [The attendance totalizer is incorrect.#3870](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/3870)
=> updated calculation of percentage

public/locales/en/attendance.json, public/locales/es/alert-message.json, public/locales/es/attendance.json, src/common/components/Navbar/index.jsx, src/js_modules/navbar/DesktopNav.jsx, src/pages/cohort/[cohortSlug]/assignments.jsx, src/pages/cohort/[cohortSlug]/attendance.jsx, src/pages/how-to/[slug]/index.jsx
>PR created for issue [It's not showing the attendance when coming from the admin #3907](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/3907)
=> academy queryString for `/cohort/{slug}/attendance` and fix 404 in `/how-to/{slug}`

src/common/services/breathecode.js, src/js_modules/assignmentHandler/index.jsx, src/pages/how-to/[slug]/index.jsx
>- [Quitar la foto de los how-to #3931](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/3931)
>- [It's not allowing to mark an assignment as delivered #3942](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/3942)
=> remove image in how-to and fixed bug in `/assignments`

modifyEnv.js, public/locales/en/attendance.json, public/locales/en/dashboard.json, public/locales/en/signup.json, public/locales/es/alert-message.json, public/locales/es/attendance.json, public/locales/es/dashboard.json, public/locales/es/signup.json, src/common/components/AttendanceModal/index.jsx, src/common/components/Navbar/index.jsx, src/common/services/breathecode.js, src/js_modules/assignmentHandler/index.jsx, src/js_modules/navbar/DesktopNav.jsx, src/js_modules/signup/Summary.jsx, src/pages/cohort/[cohortSlug]/assignments.jsx, src/pages/cohort/[cohortSlug]/attendance.jsx, src/pages/how-to/[slug]/index.jsx, src/pages/signup.jsx, src/utils/index.js
>PR created for issue [Reemplaza el servicio utilizado para obtener la cohort #3924](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/3924)
=> sync main to development and updated endpoint for public cohorts

src/common/handlers/index.jsx, src/js_modules/chooseProgram/programList.jsx, src/pages/choose-program/index.jsx
>PR linked with issue [Main dashboard#3510](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/3510)
=> updated dashboard

public/locales/en/signup.json, public/locales/es/signup.json, src/common/services/breathecode.js, src/common/store/actions/signupAction.js, src/js_modules/landing/pricing.jsx, src/js_modules/signup/ChooseYourClass.jsx, src/js_modules/signup/ContactInformation.jsx, src/js_modules/signup/PaymentInfo.jsx, src/js_modules/signup/Summary.jsx, src/pages/choose-program/index.jsx, src/pages/learn-to-code/index.jsx, src/pages/signup.jsx
>PR created for issue [Flujo para el free trial#3925](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/3925)
=> Updated signup flow

public/locales/en/signup.json, public/locales/es/signup.json, src/common/store/actions/signupAction.js, src/js_modules/signup/ChooseDate.jsx, src/js_modules/signup/ChooseYourClass.jsx, src/js_modules/signup/PaymentInfo.jsx, src/js_modules/signup/Summary.jsx, src/pages/choose-program/index.jsx, src/pages/signup.jsx, src/utils/index.js
>- [When receiving the plans from POST /v1/payments/checking, check the financing_option array in the plans #3968](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/3968)
>- [Add a loading animation between steps in the sign up trial #3985](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/3985)
>- [The form to add payment information shouldn't be shown in the free trial #3986](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/3986)
>- [When doing the payment, you should pass one of the following values #3981](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/3981)
=> updated form

src/common/components/FilterModal/index.jsx
https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/3502
=> remove difficulties in lessons

public/locales/en/common.json, public/locales/es/common.json, src/common/store/actions/signupAction.js, src/js_modules/landing/pricing.jsx, src/js_modules/signup/ChooseDate.jsx, src/js_modules/signup/PaymentInfo.jsx, src/js_modules/signup/Summary.jsx, src/pages/signup.jsx
>- [Payment options for subscriptions #4001](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/4001)
>- [Flujo para el free trial #3925](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/3925)
>- [Si el ambiente es de produccion, remover el boton para iniciar sign up the coding introduction #3998](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/3998)
=> signup flow updates

src/js_modules/projects/ProjectList.jsx, src/pages/how-to/[slug]/index.jsx, src/pages/interactive-coding-tutorial/[difficulty]/[slug].jsx, src/pages/interactive-coding-tutorials/index.jsx, src/pages/interactive-exercise/[slug]/index.jsx, src/pages/interactive-exercises/index.jsx, src/pages/lessons/index.jsx
>PR created for issue [Add padding in the how-to, exercises, lessons and, projects views #4003](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/4003)
=> style fixes

package-lock.json, package.json, scripts/sitemap-generator.js
>PR created for issue [Articulos de 4geeksacademy.com estan apareciendo en el Sitemap de 4geeks.com #4024](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/4024)
=> filtered articles in sitemap without category how-to

src/common/store/actions/signupAction.js
>PR linked with issue [Payment options for subscriptions #4001](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/4001)
=> checking: remove array in cohort property

src/common/components/TeacherSidebar.jsx, src/common/services/breathecode.js, src/pages/cohort/[cohortSlug]/assignments.jsx
>PR created for issue [No se pueden ver los assignments de miami-prework #4078](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/4078)
=> Get cohort with academy and slug querystring

public/locales/en/common.json, public/locales/en/signup.json, public/locales/es/common.json, public/locales/es/signup.json, src/common/components/DirectAccessModal.jsx, src/common/store/actions/signupAction.js, src/js_modules/landing/pricing.jsx, src/js_modules/signup/PaymentInfo.jsx, src/js_modules/signup/Summary.jsx
>PR created for issue [Opciones de pago para suscripciones #4001](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/4001)
=> Updated payment options

src/common/components/LanguageSelector.jsx, src/common/components/MarkDownParser/index.jsx, src/common/components/MarkDownParser/toc.jsx, src/common/handlers/index.jsx, src/js_modules/moduleMap/module.jsx, src/lib/redirectsHandler.js, src/pages/cohort/[cohortSlug]/attendance.jsx, src/pages/how-to/[slug]/index.jsx, src/pages/interactive-coding-tutorial/[difficulty]/[slug].jsx, src/pages/interactive-exercise/[slug]/index.jsx, src/pages/lesson/[slug].jsx, src/pages/lessons/index.jsx, src/pages/project/[slug].jsx, styles/markdown.css
>- [Table of contents in the markdown reader must be one column #4121](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/4121)
=> SEO improvements, removed conditional length of cohorts (/attendance) and more

public/locales/en/assignments.json, public/locales/es/assignments.json, src/common/components/taskLabel.jsx, src/js_modules/assignmentHandler/index.jsx, src/pages/cohort/[cohortSlug]/assignments.jsx
>PR created for issue [It's not allowing to mark an assignment as ignored #4107](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/4107)
=> new status for revision_status

src/common/hooks/useModuleHandler.js
>PR created for issue [No incluir el URL del link en el mensaje de exito cuando entregaste un proyecto #3850](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/3850#event-8337537476)
=> remove link in toast message

public/locales/en/alert-message.json, public/locales/en/live-event.json, public/locales/es/alert-message.json, public/locales/es/live-event.json, src/common/components/LiveEvent.jsx, src/common/handlers/index.jsx, src/common/services/breathecode.js, src/pages/choose-program/index.jsx, src/pages/cohort/[cohortSlug]/[slug]/[version]/index.jsx, src/utils/index.js
>PR created for issue [Get LiveClasses information to use it in the events component #4088](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/4088)
=> Updates in for LiveEvent component

src/common/components/SupportSidebar/Mentoring.jsx, src/common/components/SupportSidebar/MentoringConsumables.jsx, src/common/components/SupportSidebar/MentoringFree.jsx, src/common/components/SupportSidebar/index.jsx
>PR created for issue [Add feature flag to mentorship flow #4156](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/4156)
=> feature flag for mentorship component

public/locales/en/final-project.json, public/locales/es/final-project.json, src/common/components/FinalProject/AddMember.jsx, src/common/components/FinalProject/Form.jsx, src/common/components/FinalProject/index.jsx, src/common/components/LiveEvent.jsx, src/common/components/ProgressBar/Progress.jsx, src/common/store/actions/finalProjectAction.js, src/common/store/reducers/finalProjectReducer.js, src/js_modules/chooseProgram/programList.jsx, src/pages/choose-program/index.jsx, src/pages/cohort/[cohortSlug]/[slug]/[version]/index.jsx, src/store.js, src/stories/FinalProject.stories.jsx, src/utils/index.js
>PR created for issue [Final Project mode #2877](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/2877)
=> Final project

public/locales/en/dashboard.json, public/locales/es/dashboard.json, src/common/hooks/useCohortHandler.js, src/js_modules/assignmentHandler/PopoverHandler.jsx, src/js_modules/moduleMap/module.jsx, src/pages/syllabus/[cohortSlug]/[lesson]/[lessonSlug]/index.jsx
>PR created for issues
>- [Boton de intrucciones del profesor no hace nada #4268](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/4268)
>- [The PDF files are not opening for assignments #4263](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/4263)
=> updated teacher instruction and bug in assignments

src/common/components/SupportSidebar/Mentoring.jsx, src/js_modules/landing/pricing.jsx, src/pages/choose-program/index.jsx
>PR created for issue [Start sending the context of the flag after user logged in #4289](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/4289)
=> some updates

src/common/components/LiveEvent.jsx
>PR created for issue [Si no hay live class, el evento que aparece arriba no permite acceder al link #4368](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/4368)
=> Enable link if its an event

public/locales/en/common.json, public/locales/en/live-event.json, public/locales/es/common.json, public/locales/es/live-event.json, src/common/components/LiveEvent.jsx, src/pages/choose-program/index.jsx, src/pages/cohort/[cohortSlug]/[slug]/[version]/index.jsx, src/stories/LiveEvent.stories.jsx, src/utils/index.js
>PR created for issue [Agregar mensaje explicativo de Live Classes #4371](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/4371)
=> Updated LiveEvent component

src/common/components/LiveEvent/OtherEvents.jsx, src/common/components/LiveEvent/index.jsx, src/pages/cohort/[cohortSlug]/[slug]/[version]/index.jsx, src/stories/LiveEvent.stories.jsx
>PR created for issue [Si no hay live class, el evento que aparece arriba no permite acceder al link #4368](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/4368)
=> Live Event update

src/pages/choose-program/index.jsx, src/pages/cohort/[cohortSlug]/[slug]/[version]/index.jsx
>- [No aparece componente de Live Events #4441](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/4441)
>- [Realizar `identify` de launch darkly al hacer login #4442](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/4442)
=> updated identify

src/js_modules/projects/ProjectList.jsx
=> Fix: Masonry bug in prerender

src/common/components/LiveEvent/OtherEvents.jsx, src/common/components/LiveEvent/index.jsx
>PR created for issue [Change live events url #4445](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/4445)
=> Updated event link

public/locales/en/profile.json, public/locales/en/signup.json, public/locales/es/profile.json, public/locales/es/signup.json, src/js_modules/profile/Subscriptions/handlers.js, src/js_modules/profile/Subscriptions/index.jsx, src/js_modules/signup/ChooseDate.jsx, src/js_modules/signup/Summary.jsx, src/stories/Subscriptions.stories.jsx
>PR created for issue [Cambios en la seccion subscriptions del perfil #4503](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/4503)
=> updated subscriptions

public/locales/en/program-card.json, public/locales/es/program-card.json, src/common/components/ProgramCard.jsx, src/common/store/actions/signupAction.js, src/js_modules/chooseProgram/Programs.jsx, src/js_modules/signup/Summary.jsx, src/pages/choose-program/index.jsx, src/stories/ProgramCard.stories.jsx
>PR created for issues
>- [Hacer que componente ProgramCard ignore los escenarios relacionados a planes si la cohort no esta available for saas #4424](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/4424)
>- updated payment request for trial plan
=> Update program card

src/js_modules/profile/Subscriptions/index.jsx
>PR linked with issue [Modificaciones en tarjeta de subscriptions #4522](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/4522)
=> title of plan in subscriptions

src/pages/interactive-coding-tutorial/[difficulty]/[slug].jsx, styles/markdown.css
>PR created for issue [website is not responsive on assets views #4517](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/4517)
=> Fix: Whitespace in mobile

public/sitemap.xml, src/common/components/Navbar/index.jsx
https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/4550
=> el hamburger del menu y el logo no carga si Javascript esta desactivado

src/common/store/actions/signupAction.js, src/js_modules/signup/Summary.jsx
>- [No se estan mostrando todos los financing options #4631](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/4631)
>- [No se estan mostrando los PlanFinancing en My Subscriptions #4626](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/4626)
=> updated financing options in signup flow

src/pages/[uid].jsx
>PR created for issue [Se puede utilizar slice machine en nuestro projecto de next.js? #4173](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/4173)
=> Preview for prismic pages in status draft

src/common/components/PublicCourseCard.jsx, src/stories/PublicCourseCard.stories.jsx
https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/4415
=> add background again

src/common/components/LiveEvent/MainEvent.jsx, src/common/components/LiveEvent/OtherEvents.jsx
https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/4544
=> add rerender text every minute

public/locales/en/live-event.json, public/locales/es/live-event.json, src/common/components/LiveEvent/MainEvent.jsx, src/common/components/LiveEvent/OtherEvents.jsx, src/common/components/LiveEvent/index.jsx, src/utils/index.js
>PR created for issue [Correcciones al componente LiveEvent #4690](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/4690)
=> updated time format

src/common/store/actions/signupAction.js, src/pages/[uid].jsx
>PR created for issue [No esta pasando el plan cuando pide los service items #4718](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/4718)
=> fix bug in checking

src/pages/checkout.jsx
>PR created for issue [Permitir comprar por mentorship_service_set o event_type_set #4389](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/4389)
=> auto select cohort if plan has not available cohorts

src/common/components/MktTwoColumnSideImage.jsx
https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/4352
=> remove border radious

src/common/components/MktPartners.jsx, src/common/components/MktTechnologies.jsx
https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/4739
=> fix details in partners component

src/common/components/MktRecommendedCourses.jsx, src/common/components/MktTechnologies.jsx, src/common/components/PublicCourseCard.jsx
https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/4809
=> add validation to default case in recommended course

slices/RoadMap/index.jsx, src/common/components/MktShowPrices.jsx, src/common/hooks/useStyle.js, src/pages/thank-you.jsx
>PR created for issue [No se ven los textos del waiting list #4825](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/4825)
=> updated 'thank-you' page for darkmode

src/common/components/MktTechnologies.jsx
https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/4738
=> fix details in technologies component

.slicemachine/assets/customtypes/page/mocks.json, .slicemachine/prismicio.d.ts, customtypes/page/index.json, src/common/store/actions/subscriptionAction.js, src/js_modules/profile/Subscriptions/ButtonHandler.jsx, src/js_modules/profile/Subscriptions/handlers.jsx
>PR created for issue [No se debe permitir cancelar un PlanFinancing #4643](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/4643)
=> updates for subscription section

slices/RecommendedCourses/index.jsx, src/common/components/MktRecommendedCourses.jsx, src/common/components/PublicCourseCard.jsx, src/pages/how-to/[slug]/index.jsx, src/pages/interactive-coding-tutorial/[slug].jsx, src/pages/interactive-exercise/[slug]/index.jsx, src/pages/lesson/[slug].jsx
https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/4809
=> fix details in recommended courses

src/common/components/MktRecommendedCourses.jsx, src/common/components/PublicCourseCard.jsx, src/pages/how-to/[slug]/index.jsx
https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/4797
=> Make recommended courses component swipable

src/pages/checkout.jsx
>PR created for issue [El boton de "Go back" solo debe existir si yo escogi una cohort manualmente #4796](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/4796)
=> hide button "go back"

src/common/components/MktTechnologiesPills.jsx
https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/4824
=> fix bug at technologies pills

slices/RecommendedCourses/index.jsx, src/common/components/MktRecommendedCourses.jsx, src/common/components/MktTechnologies.jsx, src/common/components/MktTestimonials.jsx, src/pages/how-to/[slug]/index.jsx, src/pages/interactive-coding-tutorial/[slug].jsx
https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/4923
https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/4937
=> El componente MktRecommendedCourses debe tener mas padding

src/common/components/MktTestimonials.jsx
>PR created for issue [Uso de total rating para estrellas en MktTestimonials #4927](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/4927)
=> updated star rating for testimonials component

src/common/components/MktTestimonials.jsx
https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/4937
=> add defualt endpoint to testimonials

src/common/components/Footer.jsx, src/common/components/MktEventCards.jsx, src/js_modules/checkout/ChooseDate.jsx, src/js_modules/checkout/ChooseYourClass.jsx, src/js_modules/checkout/ContactInformation.jsx, src/js_modules/checkout/PaymentInfo.jsx, src/js_modules/checkout/Stepper.jsx, src/js_modules/checkout/Summary.jsx, src/pages/checkout.jsx, styles/theme.js
>- [Cambio en el diseño del summary en el checkout #4926](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/4926)
>- [El boton de "Go back" solo debe existir si yo escogi una cohort manualmente #4796](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/4796)
=> Style updates for checkout page

src/common/components/EventCard.jsx, src/common/components/MktEventCards.jsx
>- [Crear componente MktEventCards para landing de workshops #4913](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/4913)
>- [Agregar componente MktEvents a prismic #4740](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/4740)
=> Updated event links

public/locales/en/signup.json, public/locales/es/signup.json, src/js_modules/checkout/ContactInformation.jsx
>PR created for issue [El Phone number debe ser opcional en el checkout #4955](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/4955)
=> field of phone number optional

src/common/components/Heading.jsx, src/common/components/MktShowPrices.jsx, src/common/components/Navbar/index.jsx, src/common/components/ShowPrices.jsx, src/common/components/UpgradeExperience.jsx, src/js_modules/navbar/DesktopNav.jsx, src/js_modules/navbar/MobileNav.jsx, styles/globals.css
>PR created for issue [Se deben mostrar los cursos de marketing en el navbar #4848](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/4848)
=> Upgrade experience list to get courses

src/common/components/Navbar/index.jsx
>PR linked with issue [UpgradeExperience component #4255](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/4255)
=> Marketing courses to show in navbar

public/locales/en/common.json, public/locales/es/common.json, src/common/components/MktRecommendedCourses.jsx, src/common/components/MktTechnologiesPills.jsx, src/common/components/PublicCourseCard.jsx, src/pages/how-to/[slug]/index.jsx, src/pages/interactive-coding-tutorial/[slug].jsx, src/pages/interactive-exercise/[slug]/index.jsx, src/pages/lesson/[slug].jsx
https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/4824
https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/4905
=> fix details in pills

src/common/components/ProgramCard.jsx, src/common/store/actions/subscriptionAction.js, src/js_modules/chooseProgram/index.jsx, src/js_modules/profile/Subscriptions/index.jsx, src/pages/choose-program/index.jsx
>PR created for issue [Se debe dejar de mostrar las cohorts free trial si ya se le hizo upgrade #5003](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/5003)
=> applied filter subscription with free trial already upgraded in choose-programs

src/common/components/PhoneInput/index.jsx, src/js_modules/checkout/ContactInformation.jsx
>PR created for issue [El Phone number debe ser opcional en el checkout #4955](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/4955)
=> Created a "require" prop for phone input

src/common/components/LiveEvent/index.jsx, src/common/components/Navbar/index.jsx, src/js_modules/chooseProgram/index.jsx, src/js_modules/navbar/MobileNav.jsx, src/pages/choose-program/index.jsx
>- [Se debe dejar de mostrar las cohorts free trial si ya se le hizo upgrade #5003](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/5003)
>- [El componente de LiveEvents debe tener mismo width que ProgramCard #4715](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/4715)
=> hide UpgradeExperience and fix filter for subscription courses

public/locales/en/navbar.json, public/locales/es/navbar.json, src/common/components/Navbar/index.jsx, src/js_modules/navbar/DesktopItem.jsx
>PR created for issue [Se deben mostrar los cursos de marketing en el navbar #4848](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/4848)
=> marketing courses in navbar

src/common/components/EventCard.jsx, src/common/components/MktEventCards.jsx
>PR created for issue [Agregar componente MktEvents a prismic#4740](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/4740)
=> MktEvents update

src/common/components/LanguageSelector.jsx
>PR created for issue [Cuando está el traductor de google para el sitio, la aplicación se rompe. #5019](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/5019)
=> fix bug with translations of google

src/pages/how-to/[slug]/index.jsx, src/pages/interactive-coding-tutorial/[slug].jsx, src/pages/interactive-exercise/[slug]/index.jsx, src/pages/lesson/[slug].jsx
>PR created for issue [EL side call to action de los articulos debe desaparecer en movil. #5023](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/5023)
=> remove SideRecomendedCourses in mobile version

public/redirects-from-api.json, src/common/components/MktRecommendedCourses.jsx
https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/5016
=> fix space details in call to action

src/common/components/MktTwoColumnSideImage.jsx
>PR created for issue [No se ve bien el boton al hacer hover #5047](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/5047)
=> fix hover color

src/common/components/Navbar/index.jsx, src/common/components/PublicCourseCard.jsx
>-  [Se deben mostrar los cursos de marketing en el navbar #4848](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/4848)
>- [No se ve bien el boton al hacer hover #5047](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/5047)
=> updates for courses menu in navbar

src/common/components/LiveEvent/MainEvent.jsx, src/common/components/LiveEvent/index.jsx, src/common/components/PrismicTextComponent.jsx, src/common/components/SupportSidebar/Mentoring.jsx, src/common/components/SupportSidebar/MentoringConsumables.jsx, src/common/components/SupportSidebar/MentoringFree.jsx, src/common/components/SupportSidebar/index.jsx
>PR created for issue [Cambio en el componente para agendar mentorships #5018](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/5018)
=> updated Mentoring component

public/locales/en/dashboard.json, public/locales/es/dashboard.json, src/common/components/SupportSidebar/MentoringConsumables.jsx, src/common/components/SupportSidebar/MentoringFree.jsx
>PR linked with issue [Cambio en el componente para agendar mentorships #5018](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/5018)
=> Quick fixes for style in Mentory component

src/pages/index.jsx
>PR linked with issue [Cambiar font-size de h2 de las landings #5046](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/5046)
=> fix h2 in landing

src/common/components/Navbar/index.jsx, src/common/components/ShareButton.jsx, src/pages/_document.jsx
>PR created for issue [Cuando está el traductor de google para el sitio, la aplicación se rompe. #5019](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/5019)
=> disable translation

src/common/components/SupportSidebar/Mentoring.jsx, src/common/components/SupportSidebar/MentoringConsumables.jsx, src/common/components/SupportSidebar/MentoringFree.jsx
>PR created for issue [Cambio en el componente para agendar mentorships #5018](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/5018)
=> updated style for mentoring component

src/js_modules/chooseProgram/index.jsx, src/pages/choose-program/index.jsx
>PR created for issue [Wait for new recently paid cohort to be available on dashboard after 2 seconds #5049](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/5049)
=> update revalidation for cohort after subscribed

scripts/sitemap-generator/index.js, scripts/sitemap-generator/requests.js, src/pages/lesson/[slug].jsx, src/utils/url.js
>PR created for issue [Los articles no se estan publicando en el website (a menos que tengan category how-to/como) #5142](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/5142)
=> filter of lessons updated 

src/common/components/SupportSidebar/Mentoring.jsx, src/common/components/SupportSidebar/MentoringConsumables.jsx
>PR created for issue [Cambio en el componente para agendar mentorships #5018](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/5018)
=> fixed: hidden mentorship balance 

src/common/components/MktTestimonials.jsx
>PR created for issue [Agregar border a cards de MktTestimonials #5084](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/5084)
=> border for testimonial card

src/common/components/MktSideRecommendedCourses.jsx, src/pages/how-to/[slug]/index.jsx
>PR created for issue [Agregar version mobile de MktSideRecommendedCourses #5133](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/5133)
=> updated MktSideRecomendedCourses component

src/common/components/MktSideRecommendedCourses.jsx, src/pages/how-to/[slug]/index.jsx, src/pages/interactive-coding-tutorial/[slug].jsx, src/pages/interactive-exercise/[slug]/index.jsx, src/pages/lesson/[slug].jsx
>- [Agregar version mobile de MktSideRecommendedCourses #5133](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/5133)
>- [Cambiar diseño de MktSideRecommendedCourses #5092](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/5092)
=> updated style

src/common/components/MktTestimonials.jsx, src/common/components/SupportSidebar/MentoringConsumables.jsx, src/common/components/SupportSidebar/MentoringFree.jsx
>- [Agregar border a cards de MktTestimonials #5084](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/5084)
>- [Cambio en el componente para agendar mentorships #5018](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/5018)
=> updated style for testimonial card

src/common/components/MktSideRecommendedCourses.jsx, src/pages/how-to/technology/[technology].jsx, src/pages/interactive-coding-tutorials/technology/[technology].jsx, src/pages/interactive-exercises/technology/[technology].jsx, src/pages/lessons/technology/[technology].jsx
>PR created for issue [Algunas tecnologias en los tutoriales dan 404 #5194](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/5194)
=> Fix bug in page of technologies 

src/common/components/SupportSidebar/Mentoring.jsx, src/common/components/SupportSidebar/MentoringConsumables.jsx
>PR created for issue [Cambio en el componente para agendar mentorships #5018](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/5018)
=> fix balance of consumables

src/js_modules/checkout/ContactInformation.jsx
>PR created PR for issue [Si el plan tiene has_waiting_list=true, se debe redireccionar a la vista de waiting list #5122](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/5122)
=> update submit function

public/locales/en/assignments.json, public/locales/es/assignments.json, public/sitemap.xml, src/common/components/DottedTimeline.jsx, src/js_modules/assignmentHandler/PopoverHandler.jsx, src/pages/cohort/[cohortSlug]/assignments.jsx
https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/4141
=> Fixes reporte de entregables

src/common/hooks/useCohortHandler.js, styles/globals.css
>- [Agregar mas padding a los textos con formato latex #5292](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/5292)
>- [Esconder modulos que tengan 0 actividades #5307](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/5307)
=> update styles and hide modules with 0 activities

src/common/components/LiveEvent/MainEvent.jsx, src/common/components/LiveEvent/OtherEvents.jsx, src/common/components/LoaderScreen.jsx, src/common/components/Timer.jsx, src/js_modules/checkout/ContactInformation.jsx, src/js_modules/checkout/Stepper.jsx, src/js_modules/cohortSidebar/avatarUser.jsx, src/pages/interactive-coding-tutorial/[slug].jsx, src/pages/interactive-exercise/[slug]/index.jsx, src/pages/workshops/[event_slug].jsx
>- [Crear landing de workshops #5152](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/5152#top)
>- [Cambiar diseño de checkout en mobile #5014](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/5014)
>- [Quitar call to action de ejercicios interactivos y proyectos #5104](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/5104)
=> updated workshops page and more

src/pages/workshops/[event_slug].jsx
>PR created for issue [Rediseño de landing para entrar a workshops #5335](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/5335#top)
=> fix css bug

src/common/components/Forms/Register.jsx, src/common/components/ShowOnSignup.jsx, src/js_modules/checkout/ContactInformation.jsx
>PR created for issue [Revertir cambios hechos solicitados antes en el issue #5421](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/5421#top)
=> Revert changes with `is_email_validated`

src/common/components/SupportSidebar/index.jsx
>PR created for issue [Si no hay mentorship_service disponible, no se debe mostrar la caja de mentorias #5476](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/5476)
=> Conditional for SupportSidebar component

src/pages/cohort/[cohortSlug]/attendance.jsx
>PR created for issue [El attendance marca cero #5477](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/5477)
=> Fix bug in attendance page

src/js_modules/checkout/ChooseYourClass.jsx, src/js_modules/checkout/Summary.jsx, src/pages/checkout.jsx
>- [Si solo hay una opcion de plan se debe auto escoger #5458](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/5458)
>- [Al registrarte se debe reenviar al summary de checkout con el base plan #5496](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/5496)
=> update checkout page

src/pages/how-to/technology/[technology].jsx, src/pages/interactive-coding-tutorials/technology/[technology].jsx, src/pages/interactive-exercises/technology/[technology].jsx, src/pages/lessons/technology/[technology].jsx
>PR linked with issue [Problemas con los URL #5471](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/5471)
=> updated technology pages

src/common/components/Forms/Register.jsx, src/common/components/Forms/validationSchemas.js, src/js_modules/checkout/Summary.jsx
>PR created for issue[El numero de telefono debe ser opcional #5500](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/5500#event-9620997665)
=> remove phone requirements

src/common/components/MarkDownParser/MDComponents/index.jsx, src/pages/workshops/[event_slug].jsx
>PR created for issue [Crear landing de workshops #5152](https://github.com/orgs/4GeeksAcademy/projects/10/views/5?filterQuery=assignee%3AArielCalisaya&pane=issue&itemId=28001093)
=> updated style of workshop

src/common/components/Timer.jsx, src/pages/workshops/[event_slug].jsx
>PR linked with issue
>- [Crear landing de workshops #5152](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/5152)
=> auto remove digits with 0 in timer

public/locales/en/workshops.json, public/locales/es/workshops.json, src/common/components/ComponentOnTime.jsx, src/pages/workshops/[event_slug].jsx
>- [Cambiar textos para cuando el evento no ha empezado en el landing de workshops #5519](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/5519)
>- [Si el evento ya empezo debe permitir unirse directamente #5517](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/5517)
>- [Los usuarios se deben registrar en el evento si no ha iniciado #5520](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/5520)
=> updated workshops texts and functions

src/common/components/Forms/Register.jsx, src/common/components/ShowOnSignup.jsx, src/js_modules/checkout/ContactInformation.jsx, src/pages/workshops/[event_slug].jsx
>PR created for issue [Crear diseño del landing de workshops cuando ya se termino #5534](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/5534)
=> updated styles for ended workshops

public/locales/en/signup.json, public/locales/es/signup.json, src/common/context/AuthContext.jsx
>PR created for issue [Mostrar modal si en login el request falla y retorna el silent_code=email-not-validated en el error #5468](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/5468)
=> updated error messages for login

public/locales/en/signup.json, public/locales/es/signup.json, src/common/components/SupportSidebar/MentoringConsumables.jsx, src/common/context/AuthContext.jsx, src/common/store/actions/signupAction.js, src/js_modules/checkout/ServiceSummary.jsx, src/js_modules/moduleMap/modalInfo.jsx, src/pages/checkout.jsx
>- [Crear vista de checkout de workshops y mentorias #5126](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/5126)
>- [Error en flujo de register #5577](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/5577)
=> Fix bug and updates

public/locales/en/signup.json, public/locales/es/signup.json, src/js_modules/checkout/ServiceSummary.jsx, src/js_modules/moduleMap/modalInfo.jsx
>PR linked with issue [Crear vista de checkout de workshops y mentorias #5126](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/5126)
=> Style updates

src/common/components/Forms/Register.jsx, src/common/components/ShowOnSignup.jsx, src/common/context/AuthContext.jsx, src/js_modules/checkout/ContactInformation.jsx, src/js_modules/moduleMap/modalInfo.jsx, src/lib/types.js, src/pages/login/index.jsx
>PR created for issue [Mostrar modal si en login el request falla y retorna el silent_code=email-not-validated en el error #5468](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/5468)
=> modal in register view

public/locales/en/common.json, public/locales/es/common.json, src/common/components/Forms/Register.jsx, src/common/components/ShowOnSignup.jsx, src/js_modules/checkout/ContactInformation.jsx, src/js_modules/moduleMap/modalInfo.jsx, src/pages/checkout.jsx, src/pages/login/index.jsx
>PR created for issue [Mostrar modal en registro de que el usuario ya existe #5589](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/5589#top)
=> Confirm email modal

i18n.js, public/locales/en/signup.json, public/locales/es/signup.json, src/common/components/Footer.jsx, src/common/components/HelpComponent.jsx, src/common/components/Icon/index.jsx, src/common/components/MarkDownParser/ContentHeading.jsx, src/common/components/MktTestimonials.jsx, src/common/components/Navbar/index.jsx, src/common/components/SupportSidebar/MentoringConsumables.jsx, src/common/components/SupportSidebar/index.jsx, src/js_modules/assignmentHandler/PopoverHandler.jsx, src/js_modules/assignmentHandler/index.jsx, src/js_modules/navbar/DesktopItem.jsx, src/js_modules/navbar/MobileNav.jsx, src/js_modules/profile/Subscriptions/index.jsx, src/pages/_app.jsx, src/pages/_document.jsx, src/pages/cohort/[cohortSlug]/[slug]/[version]/index.jsx, src/pages/interactive-exercise/[slug]/index.jsx, src/pages/mentorship/index.jsx, src/pages/syllabus/[cohortSlug]/[lesson]/[lessonSlug]/index.jsx, src/pages/workshops/[event_slug].jsx
>PR created for issue [Cuando está el traductor de google para el sitio, la aplicación se rompe. #5019](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/5019)
=> Fix bug that breaks the page when changes to another page with google translation enabled

src/common/components/Navbar/index.jsx, src/js_modules/chooseProgram/index.jsx
>PR created for issue : [Se esta mostrando el curso gratis en el dashboard #5683](https://github.com/breatheco-de/breatheco-de/issues/5683)
=> fix filter of marketingCourses

src/common/components/MktEventCards.jsx, src/common/components/Navbar/index.jsx, src/common/handlers/index.jsx
>- [Los programas ya finalizados no deben aparecer repetidos #5394](https://github.com/breatheco-de/breatheco-de/issues/5394)
=> fix filter for finished cohorts

public/locales/en/signup.json, public/locales/es/navbar.json, public/locales/es/signup.json, src/common/components/MktSideRecommendedCourses.jsx, src/js_modules/checkout/SelectServicePlan.jsx, src/pages/checkout.jsx, src/pages/how-to/[slug]/index.jsx, src/pages/lesson/[slug].jsx
>- [Agregar escenario de consumibles en landing de workshops #5523](https://github.com/breatheco-de/breatheco-de/issues/5523)
>- [Paso para escoger el plan en checkout #5621](https://github.com/breatheco-de/breatheco-de/issues/5621)
>- [Cambiar el CTA Side en mobile #5560](https://github.com/breatheco-de/breatheco-de/issues/5560)
=> update select service view and fix bug

src/common/components/ShowOnSignup.jsx, src/common/hooks/useSubscribeToPlan.jsx, src/pages/workshops/[event_slug].jsx
>PR created for issue [Cuando acepte la modal en la que se registra en 4geeks standard se debe refrescar la vista #5868](https://github.com/breatheco-de/breatheco-de/issues/5868)
=> refetch after signup success in workshops

scripts/sitemap-generator/sitemap-config.js, src/pages/[uid].jsx, src/pages/how-to/[slug]/index.jsx, src/pages/interactive-coding-tutorial/[slug].jsx, src/pages/interactive-exercise/[slug]/index.jsx, src/pages/lesson/[slug].jsx, src/pages/mentorship/index.jsx, src/pages/read/[slug].jsx
>PR created for issue [En las paginas estaticas se debe incluir los h1 en el raw HTML #5839](https://github.com/breatheco-de/breatheco-de/issues/5839)
=> structured data for website

src/common/components/PublicProfile.jsx
=> fix bug in workshops

src/common/components/FinalProject/Form.jsx, src/common/services/breathecode.js
https://github.com/breatheco-de/breatheco-de/issues/4823
=> Fix final project

src/common/components/PublicProfile.jsx
>PR created for issue [No se esta mostrando la imagen de perfil de los hosts #5893](https://github.com/breatheco-de/breatheco-de/issues/5893)
=> image for host_user in workshops

src/pages/interactive-coding-tutorial/[slug].jsx, src/pages/interactive-exercise/[slug]/index.jsx, src/pages/lesson/[slug].jsx
>PR created for issue [No se esta mostrando el title de las lessons #5898](https://github.com/breatheco-de/breatheco-de/issues/5898)
=> h1 in lesson page

src/pages/how-to/[slug]/index.jsx, src/pages/how-to/index.jsx
>PR created for issue [Mostrar tambien los asset de tipo LESSON en /how-to #5904](https://github.com/breatheco-de/breatheco-de/issues/5904)
=> include lesson and article asset in how-to page

public/locales/en/footer.json, public/locales/es/footer.json, src/common/components/Footer.jsx, src/common/components/LiveEvent/index.jsx, src/common/components/Navbar/index.jsx, src/pages/login/index.jsx
>PR created for issue [Cambios para White Label #5912](https://github.com/breatheco-de/breatheco-de/issues/5912)
=> white label changes

src/js_modules/profile/Subscriptions/handlers.jsx
>PR Linked with issue [Esta mostrando FREE TRIAL aunque no tiene free trial #5919](https://github.com/breatheco-de/breatheco-de/issues/5919)
=> fix bug in ShowPrices Component

src/common/components/Forms/Register.jsx
https://github.com/breatheco-de/breatheco-de/issues/5878
=> add consent checkbox to register form

scripts/redirects-generator.js, src/common/components/Footer.jsx, src/common/components/Icon/components.jsx, src/common/components/Icon/index.jsx, src/common/components/MktSideRecommendedCourses.jsx, src/js_modules/navbar/DesktopItem.jsx, src/pages/checkout.jsx, src/pages/lesson/[slug].jsx
>PR linked with:
>- [Verificar que el sitemap y los redirects de la pagina no incluyas assets sino solamente de las academias en WHITE_LABLE_ACADEMY. #5945](https://github.com/breatheco-de/breatheco-de/issues/5945)
>- [Actualizar recomendaciones de cursos para que solo sean de las white label academies y features #5928](https://github.com/breatheco-de/breatheco-de/issues/5928)
>- [Mostrar modal introductoria a 4Geeks #5847](https://github.com/breatheco-de/breatheco-de/issues/5847)
=> fix hydration error in dev mode

src/common/components/MarkDownParser/ContentHeading.jsx, src/common/components/ShowOnSignup.jsx, src/pages/syllabus/[cohortSlug]/[lesson]/[lessonSlug]/index.jsx, src/pages/workshops/[event_slug].jsx
>PR created for issue
>- [Se esta agregnado -es en el slug del asset para traerselos en español #5917](https://github.com/breatheco-de/breatheco-de/issues/5917)
>- [Boton educar en github esta detras del titulo #5916](https://github.com/breatheco-de/breatheco-de/issues/5916)
>- [Cambiar los previews de los eventos a gif animados #5958](https://github.com/breatheco-de/breatheco-de/issues/5958)
=> fix link for markdown in syllabus pages

src/common/components/InfiniteScroll.jsx, src/common/components/ProjectsLoader.jsx, src/js_modules/projects/ProjectList.jsx, src/pages/how-to/index.jsx, src/pages/interactive-coding-tutorials/index.jsx, src/pages/interactive-exercises/index.jsx, src/pages/lessons/index.jsx
https://github.com/breatheco-de/breatheco-de/issues/5948
=> Fix no js pagination

public/locales/en/final-project.json, public/locales/es/final-project.json, src/common/components/FinalProject/AddMember.jsx, src/common/components/FinalProject/Modal.jsx, src/pages/cohort/[cohortSlug]/[slug]/[version]/index.jsx
https://github.com/breatheco-de/breatheco-de/issues/5967
=> fix no members message on final project

public/locales/en/exercises.json, public/locales/es/exercises.json, src/pages/interactive-exercise/[slug]/index.jsx
https://github.com/breatheco-de/breatheco-de/issues/5895
=> fix clone link in spanish

.github/workflows/storybook.yml, src/common/components/MktSideRecommendedCourses.jsx
>PR linked with issue [Actualizar recomendaciones de cursos para que solo sean de las white label academies y features #5928](https://github.com/breatheco-de/breatheco-de/issues/5928)
=> Fix bug with componente and update storybook.yml

package.json, scripts/generate_assets.js, src/utils/requests.js
https://github.com/breatheco-de/breatheco-de/issues/6121
=> optimize requests when deploying app

src/js_modules/checkout/ContactInformation.jsx
>PR linked with issue [Modificar formulario de vista de checkout #6114](https://github.com/breatheco-de/breatheco-de/issues/6114#top)
=> fix visual bug in checking

i18n.js, public/locales/en/docs.json, public/locales/es/docs.json, src/pages/docs/[syllabusSlug]/[assetSlug]/index.jsx, src/pages/docs/[syllabusSlug]/index.jsx
https://github.com/breatheco-de/breatheco-de/issues/5815
=> add validations

src/common/components/MktRecommendedCourses.jsx, src/common/components/MktSideRecommendedCourses.jsx, src/common/components/PublicCourseCard.jsx
>PR created for issue [Utilizar coursetranslation.landing_url para redireccionar al landing de un curso #5930](https://github.com/breatheco-de/breatheco-de/issues/5930)
=> Redirect for mkt courses card

prismicio-types.d.ts, slices/OneColumn/index.jsx, slices/OneColumn/mocks.json, slices/OneColumn/model.json, slices/TitleIntroduction/mocks.json, slices/TitleIntroduction/model.json, slices/TwoColumn/index.jsx, slices/TwoColumn/mocks.json, slices/TwoColumn/model.json, src/js_modules/landing/introductionSection.jsx, src/js_modules/projects/SimpleTable.jsx, src/pages/checkout.jsx, src/pages/how-to/[slug]/index.jsx, src/pages/how-to/technology/[technology].jsx, src/pages/lesson/[slug].jsx
>PR linked with issues: 
>- [Fix 404 links #5859](https://github.com/breatheco-de/breatheco-de/issues/5859)
>- [Si voy a /checkout por defecto (sin variables en el querystring) no deberia mandarme a elegir cohort sino llevarme directo a summary con el plan de 4geeks-standard #6163](https://github.com/breatheco-de/breatheco-de/issues/6163)
=> fix link for Tag technologies

public/locales/en/common.json, public/locales/es/common.json, src/common/components/LoaderScreen.jsx, src/common/components/PricingCard.jsx, src/common/handlers/subscriptions.js, src/js_modules/checkout/ContactInformation.jsx, src/pages/checkout.jsx, src/pages/pricing.jsx
>- [Agregar plan "bootcamp" permanentemente #6187](https://github.com/breatheco-de/breatheco-de/issues/6187)
>- [ Hay mensajes en ingles en la vista de español (Free, Monthly y Yearly)](https://github.com/breatheco-de/breatheco-de/issues/5936#issuecomment-1735686443)
>- [En la vist ade checkout, si no hay un plan en el URL poner un paso para elegir el plan #6168](https://github.com/breatheco-de/breatheco-de/issues/6168)
=> updates for pricing page

public/locales/en/common.json, public/locales/es/common.json, src/common/components/PricingCard.jsx, src/common/hooks/useStyle.js, src/pages/pricing.jsx
> PR create for issue [Quitar el precio del plan bootcamp hasta nuevo aviso #6202](https://github.com/breatheco-de/breatheco-de/issues/6202#event-10596962769)
=> remove price for bootcamp

scripts/generate_assets.js, src/utils/requests.js
https://github.com/breatheco-de/breatheco-de/issues/6141
=> remove technologies get request

src/pages/api/asset/[assetSlug].js, src/utils/requests.js
https://github.com/breatheco-de/breatheco-de/issues/6142
=> Set expire time on vercel cache

public/locales/en/common.json, public/locales/es/common.json, src/js_modules/moduleMap/modalInfo.jsx, src/pages/checkout.jsx
>- [Quitar el precio del plan bootcamp hasta nuevo aviso #6202](https://github.com/breatheco-de/breatheco-de/issues/6202)
>- [Los planes son muy largos y no me estas dejando hacer scroll para revisarlos todos](https://github.com/breatheco-de/breatheco-de/issues/6168#issuecomment-1756134212)
=> update bug with email modal

src/common/components/ModalToGetAccess/index.jsx, src/pages/join/cohort/[id].jsx, src/utils/url.js
>PR created for issue [Si intento join cohort en la modal que bloquea los contenidos, con un usuario que no tiene un plan, no deberia mandarme al home #6207](https://github.com/breatheco-de/breatheco-de/issues/6207)
=> Fix bug with modal for join cohort page

src/common/context/PrivateRouteWrapper.jsx, src/js_modules/chooseProgram/index.jsx, src/pages/lesson/[slug].jsx, src/pages/lessons/index.jsx, src/pages/pricing.jsx, src/utils/variables.js
>- [En la vista de pricing debe marcar los planes que ya tiene #6241](https://github.com/breatheco-de/breatheco-de/issues/6241#event-10637160128)
>- [Articulos que no deberian estar en 4geeks.com #6192](https://github.com/breatheco-de/breatheco-de/issues/6192)
>- [Esta enviando a checkout sin el plan que se paso #6262](https://github.com/breatheco-de/breatheco-de/issues/6262)
=> fix bug in pricing and choose-program

src/common/store/actions/signupAction.js
https://github.com/breatheco-de/breatheco-de/issues/6371
=> fix error on workshops

src/common/components/ShowOnSignup.jsx
https://github.com/breatheco-de/breatheco-de/issues/6367
=> fix bug on show on signup

src/common/components/ShowOnSignup.jsx, src/common/components/UpgradeForConsumableView.jsx, src/common/hooks/useSubscribeToPlan.jsx, src/pages/checkout.jsx
>- [Se agrego una modal de pricing en la vista de checkout, deberiamos solo usar la vista de pricing para esto #6447](https://github.com/breatheco-de/breatheco-de/issues/6447#event-10836996953)
>- [No esta funcionando la modal para obtener mas consumibles #6446](https://github.com/breatheco-de/breatheco-de/issues/6446#event-10836933523)
>- [Te redirecciona al dashboard luego de registrarte en el landing de un evento #6423](https://github.com/breatheco-de/breatheco-de/issues/6423#event-10836330147)
=> fix bug with pricing modal and consumables

src/common/components/ShowOnSignup.jsx, src/common/components/UpgradeForConsumableView.jsx, src/common/hooks/useSubscribeToPlan.jsx, src/pages/checkout.jsx
>PR linked with issue [Cambiar estilos de modal para hacer upgrade del plan cuando te quedas sin consumibles #6445](https://github.com/breatheco-de/breatheco-de/issues/6445)
=> Fix bugs in showOnSignup and consumable modal

src/common/components/DottedTimeline.jsx, src/common/components/MktRecommendedCourses.jsx, src/common/components/MktTechnologies.jsx, src/common/components/ReactSelect.jsx, styles/components/customLink.js
https://github.com/breatheco-de/breatheco-de/issues/6441
https://github.com/breatheco-de/breatheco-de/issues/6300
https://github.com/breatheco-de/breatheco-de/issues/6402
https://github.com/breatheco-de/breatheco-de/issues/6403
=> fix many bugs

scripts/sitemap-generator/index.js, src/common/components/Button.jsx, src/js_modules/landing/introductionSection.jsx
>PR created for issue [Separar logicas de redireccion vs onclick en el componente button #6226](https://github.com/breatheco-de/breatheco-de/issues/6226)
=> created a custom button component

src/common/components/ShowOnSignup.jsx, src/pages/[uid].jsx
>PR linked with issue https://github.com/breatheco-de/breatheco-de/issues/6226#issuecomment-1799887477
=> Fix Prismic pages and refetch of consumables

scripts/sitemap-generator/index.js, scripts/sitemap-generator/sitemap-config.js, src/common/components/Helmet.jsx, src/js_modules/checkout/PaymentInfo.jsx, src/utils/requests.js
>- https://github.com/breatheco-de/breatheco-de/issues/6226#issuecomment-1799887477
>- [Los sitemaps se rompieron #6505](https://github.com/breatheco-de/breatheco-de/issues/6505#top)
#6505
=> Add hreflang in sitemap for content with translation

public/locales/en/footer.json, public/locales/es/footer.json, src/pages/how-to/[slug]/index.jsx, src/pages/interactive-coding-tutorial/[slug].jsx, src/pages/interactive-exercise/[slug]/index.jsx, src/pages/lesson/[slug].jsx
>- [Link roto en el footer español unicamente #6509](https://github.com/breatheco-de/breatheco-de/issues/6509)
>- [Los og-image no estan apuntando a imagenes, cada articulo tiene su thumbnail image #6512](https://github.com/breatheco-de/breatheco-de/issues/6512)
>- [Opegraph tiene links e imagenes rotas #6513](https://github.com/breatheco-de/breatheco-de/issues/6513)
>- [Link de contact en el footer esta roto, corregir a esto #6514](https://github.com/breatheco-de/breatheco-de/issues/6514)
=> fix seo bugs

src/common/components/TagCapsule.jsx, src/js_modules/moduleMap/taskHandler.jsx, src/pages/technology/[slug].jsx
>PR created for issues[Bug al entregar proyectos #6524](https://github.com/breatheco-de/breatheco-de/issues/6524)
=> fix 404 bug

next.config.js, scripts/sitemap-generator/index.js, scripts/sitemap-generator/sitemap-config.js, src/pages/technology/[slug].jsx
>PR linked for issue [Errores en landing de tecnologias #6529](https://github.com/breatheco-de/breatheco-de/issues/6529)
=> fix sitemap

public/locales/en/technologies.json, public/locales/es/technologies.json, scripts/verify-asset-file.js, src/common/components/Helmet.jsx, src/common/components/LanguageSelector.jsx, src/common/components/MarkDownParser/MDComponents/index.jsx, src/common/components/MarkDownParser/index.jsx, src/common/components/Navbar/index.jsx, src/js_modules/landing/introductionSection.jsx, src/pages/[uid].jsx, src/pages/_app.jsx, src/pages/_document.jsx, src/pages/interactive-exercise/[slug]/index.jsx, src/pages/lesson/[slug].jsx, src/pages/technology/[slug].jsx, styles/theme.js
>PR created for issue [Agregar meta description a todos los landing de tecnologias #6516](https://github.com/breatheco-de/breatheco-de/issues/6516)
=> update meta description for technology landings

public/locales/en/pricing.json, public/locales/en/signup.json, public/locales/es/signup.json, src/common/components/Faq.jsx, src/common/components/PricingCard.jsx, src/pages/pricing.jsx
https://github.com/breatheco-de/breatheco-de/issues/6560
https://github.com/breatheco-de/breatheco-de/issues/6486
=> Add dangerously set html to faq

src/common/components/MktTestimonials.jsx, src/pages/workshops/[event_slug].jsx
PR linked with issue [Landings de workshops en español estan duplicados #6541](https://github.com/breatheco-de/breatheco-de/issues/6541)
=> fix og:url

package.json, src/common/components/Icon/set/play.jsx, src/common/components/ReactPlayerV2.jsx
>PR created for issue [Agregar intro en los tutoriales interactivos y proyectos #6554](https://github.com/breatheco-de/breatheco-de/issues/6554)
=> Thumbnail for ReactPlayer component

src/common/hooks/useModuleHandler.js, src/common/views/StudentAssignments.jsx, src/js_modules/assignmentHandler/index.jsx, src/pages/cohort/[cohortSlug]/assignments.jsx
https://github.com/breatheco-de/breatheco-de/issues/6138
https://github.com/breatheco-de/breatheco-de/issues/6139
=> add delivered_at on deliver

src/common/components/ShowOnSignup.jsx, src/pages/workshops/[event_slug].jsx
https://github.com/breatheco-de/breatheco-de/issues/6265
https://github.com/breatheco-de/breatheco-de/issues/6462
=> Free for all events

src/common/components/SupportSidebar/Mentoring.jsx, src/common/components/SupportSidebar/MentoringConsumables.jsx, src/common/components/SupportSidebar/index.jsx, src/common/services/breathecode.js, src/pages/choose-program/index.jsx
>PR linked with issue [Cambios en el diseño del Dashboard #5316](https://github.com/breatheco-de/breatheco-de/issues/5316)
=> Mentoring sidebar updates

public/locales/es/navbar.json, src/common/components/ReactPlayerV2.jsx, src/js_modules/checkout/ContactInformation.jsx
PR created for issues:
>- [Esta mostrando el video aunque el proyecto no tiene #6650](https://github.com/breatheco-de/breatheco-de/issues/6650)
>- [No esta traducida la descripcion de los cursos en el navbar #6633](https://github.com/breatheco-de/breatheco-de/issues/6633)
>- [Se muestran os service items en ingles en vista de checkout #6624](https://github.com/breatheco-de/breatheco-de/issues/6624)
=> Fix conditional rendering in ReactPlayerV2 and more

src/common/components/MktTrustCards.jsx
>PR created for issue [Why trus us esta descuadraro · Issue #6687](https://github.com/breatheco-de/breatheco-de/issues/6687#event-11352447518)
=> center TrustCards componente

src/common/components/LiveEvent/MainEvent.jsx, src/common/components/LiveEvent/OtherEvents.jsx, src/common/components/LiveEvent/index.jsx, src/common/components/MarkDownParser/MDComponents/index.jsx, src/common/components/MarkDownParser/index.jsx, src/common/components/MktEventCards.jsx, src/js_modules/landing/events.jsx, src/pages/choose-program/index.jsx, src/pages/cohort/[cohortSlug]/[slug]/[version]/index.jsx, src/pages/workshops/[event_slug].jsx, src/utils/index.js, styles/globals.css
>-  [Agregar validacion de cuando un evento culmina #6701](https://github.com/breatheco-de/breatheco-de/issues/6701)
>- [Add deep anchor links to markdown reader #3816](https://github.com/breatheco-de/breatheco-de/issues/3816)
=> Fix date handling in filter and display functions and more

src/pages/workshops/[event_slug].jsx
>PR linked for issue [Agregar validacion de cuando un evento culmina · Issue #6701](https://github.com/breatheco-de/breatheco-de/issues/6701#issuecomment-1883947903)
=> Refactor Page component and add getEventData function

src/pages/workshops/[event_slug].jsx
>PR linked with issue [Agregar validacion de cuando un evento culmina #6701](https://github.com/breatheco-de/breatheco-de/issues/6701)
=> Update event variable name in getStaticProps function

src/common/components/MktTechnologiesPills.jsx
https://github.com/breatheco-de/breatheco-de/issues/6646
=> revert technologies pills links

src/common/components/MktTrustCards.jsx, src/pages/example.jsx
https://github.com/breatheco-de/breatheco-de/issues/4861
=> fix image height

.storybook/i18next.js, i18n.js, public/locales/en/call-to-action.json, public/locales/es/call-to-action.json, src/common/components/CallToActionCard.jsx, src/common/components/DynamicCallToAction.jsx, src/stories/DynamicCallToAction.stories.jsx
https://github.com/breatheco-de/breatheco-de/issues/6717
https://github.com/breatheco-de/breatheco-de/issues/6653
=> Dynamic Call to action

src/common/components/MktTrustCards.jsx
https://github.com/breatheco-de/breatheco-de/issues/4861
=> fix padding in trust cards

src/common/components/Timer.jsx
https://github.com/breatheco-de/breatheco-de/issues/6732
=> fix small counter on workshops

i18n.js, public/locales/en/syllabus.json, public/locales/es/syllabus.json, src/common/components/LanguageSelector.jsx, src/common/components/MarkDownParser/ContentHeading.jsx, src/common/context/AuthContext.jsx, src/common/context/SessionContext.jsx, src/pages/syllabus/[cohortSlug]/[lesson]/[lessonSlug]/index.jsx
>PR linked with issue [Cuando tienes un lang por defecto y accedes a una lesson de otro lang, falla #6696](https://github.com/breatheco-de/breatheco-de/issues/6696)
=> sync some fixes in development linked with redirection by user language

src/pages/workshops/[event_slug].jsx
https://github.com/breatheco-de/breatheco-de/issues/6752
=> added joined description to live events

src/common/components/FinalProject/index.jsx, src/common/components/MktEventCards.jsx
https://github.com/breatheco-de/breatheco-de/issues/6750
https://github.com/breatheco-de/breatheco-de/issues/6818
=> fix bugs at final project and mkteventcards

src/common/components/MarkDownParser/index.jsx
https://github.com/breatheco-de/breatheco-de/issues/6834
=> fix codeviewer bug wrongly grouping separated codeviewers

src/common/components/CodeViewer.jsx
https://github.com/breatheco-de/breatheco-de/issues/6842
=> fix scrollbar bug when running code

src/common/components/JoinCohort.jsx
https://github.com/breatheco-de/breatheco-de/issues/6850
=> fix image logo size on join cohort

public/locales/en/navbar.json, public/locales/es/navbar.json, src/common/components/Icon/set/microphone.jsx, src/pages/podcast.jsx
>PR created for issue [Agregar link al podcast en el navbar · Issue #6873](https://github.com/breatheco-de/breatheco-de/issues/6873)
=> Add podcast menu item and icon

src/common/components/SupportSidebar/MentoringConsumables.jsx, src/common/components/SupportSidebar/MentoringFree.jsx
https://github.com/breatheco-de/breatheco-de/issues/6854
=> Fix mentorship list

slices/InfoCards/index.js, src/common/components/MktInfoCards.jsx
https://github.com/breatheco-de/breatheco-de/issues/6810
=> Add margin prop to info cards

src/pages/cohort/[cohortSlug]/student/[studentId]/index.jsx
https://github.com/breatheco-de/breatheco-de/issues/6867
=> round nps percentage

src/common/components/CodeViewer.jsx, src/common/components/MarkDownParser/index.jsx
https://github.com/breatheco-de/breatheco-de/issues/6899
=> Introducir el "path" para el CodeViewer

prismicio-types.d.ts, slices/TitleIntroduction/index.jsx, slices/TitleIntroduction/mocks.json, slices/TitleIntroduction/model.json, src/common/components/MktRecommendedCourses.jsx, src/common/components/MktTestimonials.jsx, src/common/components/MktTwoColumnSideImage.jsx, src/js_modules/landing/introductionSection.jsx, src/pages/lesson/[slug].jsx
https://github.com/breatheco-de/breatheco-de/issues/6944
https://github.com/breatheco-de/breatheco-de/issues/6949
=> Fix recommended courses

prismicio-types.d.ts, slices/InfoCards/index.js, slices/InfoCards/mocks.json, slices/InfoCards/model.json, src/common/components/MktInfoCards.jsx, src/pages/example.jsx
https://github.com/breatheco-de/breatheco-de/issues/6950
=> Agregarle padding al componente de `InfoCards en mobil

src/common/components/MarkDownParser/MDComponents/index.jsx, src/common/components/OnlyFor.jsx, src/pages/syllabus/[cohortSlug]/[lesson]/[lessonSlug]/index.jsx, src/stories/Onlyfor.stories.jsx
>PR created for issue [No esta permitiendo entrar a las lessons #6958](https://github.com/breatheco-de/breatheco-de/issues/6958)
=> Update Onlyfor component and fix bug in syllabus

public/locales/en/student.json, src/common/components/DottedTimeline.jsx, src/common/components/PopoverTaskHandler.jsx, src/common/store/actions/signupAction.js, src/common/views/StudentAssignments.jsx, src/js_modules/checkout/PaymentInfo.jsx, src/js_modules/checkout/ServiceSummary.jsx, src/js_modules/checkout/Summary.jsx, src/js_modules/moduleMap/module.jsx, src/js_modules/moduleMap/taskHandler.jsx, src/pages/cohort/[cohortSlug]/assignments.jsx, src/pages/cohort/[cohortSlug]/student/[studentId]/index.jsx
>PR. created for issues:
>- [Revision de codigo de colores para los proyectos nadamas #6946](https://github.com/breatheco-de/breatheco-de/issues/6946)
>- [Se rompio el modulo de assignments en development #6957](https://github.com/breatheco-de/breatheco-de/issues/6957)
>- [Reportar eventos del flujo para adquirir consumibles de forma individual #6921](https://github.com/breatheco-de/breatheco-de/issues/6921)
>- [Se esta reportando mal el value en checkout_summary #6973](https://github.com/breatheco-de/breatheco-de/issues/6973)
=> color change in assignment of student and more

styles/globals.css
issue: https://github.com/breatheco-de/breatheco-de/issues/6695
=> video bottom borders

src/common/components/MktSideRecommendedCourses.jsx, src/pages/how-to/[slug]/index.jsx, src/pages/lesson/[slug].jsx
https://github.com/breatheco-de/breatheco-de/issues/6855
=> redesign call to action on mobile

src/js_modules/checkout/ServiceSummary.jsx
>PR created for issue [Reportar eventos del flujo para adquirir consumibles de forma individual #6921](https://github.com/breatheco-de/breatheco-de/issues/6921)
=> Refactor dataLayer event handling in ServiceSummary component

src/pages/_app.jsx, src/pages/workshops/[event_slug].jsx
>PR created for issue [Agregar animacion de loading mientras se cargan los consumibles en vista de workshops #6992](https://github.com/breatheco-de/breatheco-de/issues/6992)
=> fix loader

src/common/components/SupportSidebar/Mentoring.jsx, src/common/components/SupportSidebar/index.jsx, src/pages/choose-program/index.jsx
https://github.com/breatheco-de/breatheco-de/issues/6968
=> fetch mentorships by service and by syllabus

src/js_modules/checkout/Summary.jsx
https://github.com/breatheco-de/breatheco-de/issues/6922
=> remove unnecesary api calls to service items data

src/pages/docs/[syllabusSlug]/[assetSlug]/index.jsx
Resolution for the issue:
https://github.com/breatheco-de/breatheco-de/issues/6275
=> Change font size of knowledge base sidebar

public/locales/en/profile.json, public/locales/es/profile.json, src/common/components/ReviewModal/index.jsx, src/common/components/profileForm.jsx, src/common/hooks/useCohortHandler.js, src/js_modules/checkout/PaymentInfo.jsx, src/js_modules/checkout/Summary.jsx, src/js_modules/chooseProgram/index.jsx, src/js_modules/profile/Information.jsx, src/pages/bootcamp/[course_slug].jsx, src/pages/checkout.jsx, src/pages/cohort/[cohortSlug]/[slug]/[version]/index.jsx, src/pages/cohort/[cohortSlug]/student/[studentId]/index.jsx
>PR created for issues
>- [Error 404, se refresca automáticamente #7059](https://github.com/breatheco-de/breatheco-de/issues/7059)
=> Fix bug and  sync changes with main branch

src/pages/bootcamp/[course_slug].jsx
>PR linked with issue [Se debe agregar el id de la cohort al que se quiere unir desde el landing del bootcamp #7050](https://github.com/breatheco-de/breatheco-de/issues/7050)
=> querystrings for first enroll button

src/common/components/ReviewModal/index.jsx, src/pages/choose-program/index.jsx
>PR created for issue [4Geeks.com - Incongruencia en límite de caracteres en cada de feedback #7009](https://github.com/breatheco-de/breatheco-de/issues/7009)
=> fix input limit in ReviewModal component

src/common/components/SupportSidebar/MentoringConsumables.jsx
>PR created for issue [No esta detectando bien la cantidad de consumibles disponible #7072](https://github.com/breatheco-de/breatheco-de/issues/7072)
=> fix bug in mentoring consumables

public/locales/en/choose-program.json, public/locales/en/common.json, public/locales/es/choose-program.json, public/locales/es/common.json, src/common/components/Feedback.jsx, src/common/components/ReviewModal/ReviewCodeRevision.jsx, src/common/components/SupportSidebar/MentoringConsumables.jsx, src/pages/bootcamp/[course_slug].jsx, src/pages/choose-program/index.jsx, src/pages/cohort/[cohortSlug]/[slug]/[version]/index.jsx
>PR linked with issue [Se debe agregar el id de la cohort al que se quiere unir desde el landing del bootcamp #7050](https://github.com/breatheco-de/breatheco-de/issues/7050)
=> Conditional for Github connection in Feedback component

src/pages/bootcamp/[course_slug].jsx
>PR created for issue [Error 404 #7076](https://github.com/breatheco-de/breatheco-de/issues/7076)
=> Refactor assignment link generation

public/locales/en/choose-program.json, public/locales/en/common.json, public/locales/es/choose-program.json, public/locales/es/common.json, src/common/components/Feedback.jsx, src/common/components/ReviewModal/ReviewCodeRevision.jsx, src/common/components/ReviewModal/index.jsx, src/common/components/SupportSidebar/MentoringConsumables.jsx, src/common/components/UpgradeForConsumableView.jsx, src/pages/bootcamp/[course_slug].jsx, src/pages/choose-program/index.jsx, src/pages/cohort/[cohortSlug]/[slug]/[version]/index.jsx, src/pages/workshops/[event_slug].jsx
>PR linked with issue [Event landing page waiting for something when user with no workshops tries to register #7069](https://github.com/breatheco-de/breatheco-de/issues/7069)
=> Sync main changes and fix event landing page when consumables of user is empty

src/common/handlers/index.js
>PR linke with issue [barra de porcentaje pasa del 100% #6863](https://github.com/breatheco-de/breatheco-de/issues/6863)
=> Refactor getCompletedTasksFromModule function to handle completed task count

public/locales/en/course.json, public/locales/es/course.json, src/common/components/Instructors.jsx, src/common/components/MktShowPrices.jsx, src/common/components/ShowPrices.jsx, src/pages/bootcamp/[course_slug].jsx
>PR created for issue [Si le doy a la opcion de financing options deberia hacer scroll hacia abajo y ubicarme de una vez en la opcion de "finance" #7108](https://github.com/breatheco-de/breatheco-de/issues/7108)
=> update financing option button

src/js_modules/moduleMap/index.jsx, src/pages/cohort/[cohortSlug]/[slug]/[version]/index.jsx
https://github.com/breatheco-de/breatheco-de/issues/7047
=> fix bug that causes tasks being generated for the wrong cohort

src/js_modules/moduleMap/index.jsx, src/pages/cohort/[cohortSlug]/[slug]/[version]/index.jsx
=> Revert "fix bug that causes tasks being generated for the wrong cohort"

src/common/components/SupportSidebar/MentoringConsumables.jsx, src/common/components/SupportSidebar/MentoringFree.jsx, src/pages/choose-program/index.jsx
https://github.com/breatheco-de/breatheco-de/issues/7146
=> fix wrong acadmies assignment to services

slices/Markdown/index.jsx
>PR created for issue [Margenes erroneos en vista de provisioning #7181](https://github.com/breatheco-de/breatheco-de/issues/7181)
=> fix grid proportion for markdown slice

next.config.js, public/locales/en/student.json, public/locales/es/student.json, slices/Markdown/index.jsx, src/common/components/DottedTimeline.jsx, src/common/components/Helmet.jsx, src/common/services/breathecode.js, src/js_modules/projects/TabletWithForm.jsx, src/pages/cohort/[cohortSlug]/student/[studentId]/index.jsx, src/pages/docs/[syllabusSlug]/[assetSlug]/index.jsx, src/pages/syllabus/[cohortSlug]/[lesson]/[lessonSlug]/index.jsx
>- [SEO Optimization para knowledge base #7136](https://github.com/breatheco-de/breatheco-de/issues/7136)
>- [Al darle al boton de Open in Github esta abriendo el asset.url #7155](https://github.com/breatheco-de/breatheco-de/issues/7155)
>- [Mensaje cuando el alumno no a atentido a ningun workshop #7167](https://github.com/breatheco-de/breatheco-de/issues/7167)
=> seo for docs page and more

next.config.js, public/locales/en/common.json, public/locales/es/common.json, scripts/prepare-asset-data.js, src/common/components/MktEventCards.jsx, src/common/components/Navbar/index.jsx, src/js_modules/navbar/MobileNav.jsx, src/js_modules/projects/TabletWithForm.jsx, src/pages/choose-program/index.jsx
>- [Desaparecer upgrade experiences hasta que sepamos que hacer con eso #7194](https://github.com/breatheco-de/breatheco-de/issues/7194#event-12428436026)
>- [Boton para cambiarse al español en el video introductorio #7193](https://github.com/breatheco-de/breatheco-de/issues/7193)
=> hide upgrade experience button from navbar and more

src/common/components/MktSideRecommendedCourses.jsx
>PR created for issue [Utiliza el color del curso para el componente #7201](https://github.com/breatheco-de/breatheco-de/issues/7201)
=> update background of icon

public/locales/en/dashboard.json, public/locales/es/dashboard.json, src/common/components/ReviewModal/index.jsx, src/common/views/StudentAssignments.jsx, src/js_modules/assignmentHandler/index.jsx, src/pages/api/download/file.js
>PR linked with issue [Usar extension si el archivo no tiene type #7219](https://github.com/breatheco-de/breatheco-de/issues/7219)
=> Show file list in review modal and update download functionality for octet-stream files

public/locales/en/dashboard.json, public/locales/es/dashboard.json, src/js_modules/moduleMap/module.jsx, src/pages/cohort/[cohortSlug]/[slug]/[version]/index.jsx
https://github.com/breatheco-de/breatheco-de/issues/6845
=> Pending mandatory projects

public/locales/en/live-event.json, public/locales/es/live-event.json, src/common/components/LiveEvent/MainEvent.jsx, src/common/components/LiveEvent/index.jsx, src/pages/choose-program/index.jsx, src/pages/cohort/[cohortSlug]/[slug]/[version]/index.jsx
https://github.com/breatheco-de/breatheco-de/issues/7174
=> Add start class message

package-lock.json, src/common/components/LiveEvent/index.jsx, src/js_modules/moduleMap/index.jsx, src/pages/cohort/[cohortSlug]/[slug]/[version]/index.jsx
=> Fix bug when press start module

package-lock.json, src/common/components/LiveEvent/index.jsx, src/js_modules/moduleMap/index.jsx, src/pages/cohort/[cohortSlug]/[slug]/[version]/index.jsx
=> Revert "Fix bug when press start module"

public/sitemap.xml, src/common/components/PaginationView/index.jsx
https://github.com/breatheco-de/breatheco-de/issues/7320
=> fix canonical link on paginated articles

src/common/store/actions/signupAction.js, src/js_modules/navbar/MobileNav.jsx
https://github.com/breatheco-de/breatheco-de/issues/7256
https://github.com/breatheco-de/breatheco-de/issues/7255
=> fix self-paced link missing and round price

src/common/components/CallToActionCard.jsx, src/common/components/MktSideRecommendedCourses.jsx
https://github.com/breatheco-de/breatheco-de/issues/7321
=> Change heading on sidebar components for spans

src/pages/syllabus/[cohortSlug]/[lesson]/[lessonSlug]/index.jsx
https://github.com/breatheco-de/breatheco-de/issues/7277
=> Se debe agregar el titulo de la pagina en el tab de vistas internas

src/pages/interactive-coding-tutorial/[slug].jsx, src/pages/interactive-exercise/[slug]/index.jsx
https://github.com/breatheco-de/breatheco-de/issues/7310
=> Fix consent link

src/js_modules/navbar/DesktopNav.jsx, src/js_modules/navbar/MobileNav.jsx
>PR created for issue [Quitar syllabus de DS y FS del navbar #7248](https://github.com/breatheco-de/breatheco-de/issues/7248)
=> remove read content

src/common/components/MktRecommendedCourses.jsx
>PR linked with issue [Los botones de empezar a aprender en el home deben llevarte a los cursos
#7207](https://github.com/breatheco-de/breatheco-de/issues/7207)
=> default id for MktRecommendedCourses

src/common/components/MktRecommendedCourses.jsx
PR linked with issue [Los botones de empezar a aprender en el home deben llevarte a los cursos
#7207](https://github.com/breatheco-de/breatheco-de/issues/7207)
=> update default id for courses component

src/common/components/CohortSideBar.jsx, src/js_modules/cohortSidebar/avatarUser.jsx
>PR created for issue [El profesor debe poder abrir el dashboard de un estudiante desde su foto #7389](https://github.com/breatheco-de/breatheco-de/issues/7389)
=> Send to student info page if teacher click to student avatar

src/pages/login/index.jsx
https://github.com/breatheco-de/breatheco-de/issues/7292
=> fix redirect when user logs in from github

src/common/components/Navbar/index.jsx
https://github.com/breatheco-de/breatheco-de/issues/7345
=> Hide self paced option from navbar when the user is part of a bootcamp

src/js_modules/moduleMap/taskHandler.jsx
https://github.com/breatheco-de/breatheco-de/issues/7048
=> Add message icon when there is a comment by the teacher

src/common/views/FinalProjects.jsx, src/pages/cohort/[cohortSlug]/[slug]/[version]/index.jsx
https://github.com/breatheco-de/breatheco-de/issues/7307
=> Open student report when you click on a final project member

src/common/components/ReviewModal/index.jsx, src/js_modules/checkout/PaymentInfo.jsx, src/js_modules/checkout/Summary.jsx
>PR created for issue [Si no esta sincronizado con rigobot no debes pedir los code reviews #7428](https://github.com/breatheco-de/breatheco-de/issues/7428)
=> Fix infinite loading in ReviewModal

public/locales/en/syllabus.json, public/locales/es/syllabus.json, src/js_modules/syllabus/TimelineSidebar.jsx, src/pages/syllabus/[cohortSlug]/[lesson]/[lessonSlug]/index.jsx
https://github.com/breatheco-de/breatheco-de/issues/7424
=> Show teacher instructions on sidebar

src/pages/checkout.jsx
>PR created for issue [Se esta enviando siempre que se quiere pagar con un solo pago #7458](https://github.com/breatheco-de/breatheco-de/issues/7458)
=> fix bug autoselect financing option by querystring

src/common/components/MarkDownParser/MDComponents/index.jsx
>PR created for issue [Links relativos que empiezan con # estan rotos #7487](https://github.com/breatheco-de/breatheco-de/issues/7487#event-13138070648)
=> Update and fix bug in markdown link

src/common/components/ReviewModal/CodeReview.jsx
https://github.com/breatheco-de/breatheco-de/issues/7359
=> Use markdown parser to display the teachers comment

src/common/components/MarkDownParser/index.jsx, src/common/components/MktRecommendedCourses.jsx, src/common/components/ShowPrices.jsx
>- [No esta centrado el componente de cursos en el home #7515](https://github.com/breatheco-de/breatheco-de/issues/7515)
>- [El componente de pricing debe decir algo diferente para subscriptions #7372](https://github.com/breatheco-de/breatheco-de/issues/7372)
=> fix visual bug with margin of card

src/js_modules/chooseProgram/Programs.jsx
https://github.com/breatheco-de/breatheco-de/issues/7507
=> Fix upgrade button

src/common/components/CohortSideBar.jsx
https://github.com/breatheco-de/breatheco-de/issues/7415
=> Fix show more students

public/locales/en/dashboard.json, public/locales/es/dashboard.json, src/common/components/CallToAction.jsx, src/common/components/Footer.jsx, src/common/hooks/useCohortHandler.js, src/pages/cohort/[cohortSlug]/[slug]/[version]/index.jsx
https://github.com/breatheco-de/breatheco-de/issues/7522
=> Go to last module on saas cohorts

src/js_modules/checkout/ServiceSummary.jsx
https://github.com/breatheco-de/breatheco-de/issues/7480
=> Fix layout on consumables checkout

public/locales/en/choose-program.json, public/locales/es/choose-program.json, src/common/components/Feedback.jsx
https://github.com/breatheco-de/breatheco-de/issues/7392
=> Small changes on Feedback component

src/common/components/MktSideRecommendedCourses.jsx
https://github.com/breatheco-de/breatheco-de/issues/7526
=> Fix bug in side recommended courses

src/common/components/Navbar/index.jsx
https://github.com/breatheco-de/breatheco-de/issues/7593
=> Remove self-pased option from navbar when the utm_medium is academy

src/common/components/DottedTimeline.jsx, src/common/components/ReviewModal/index.jsx
https://github.com/breatheco-de/breatheco-de/issues/7519
=> fix bug with task title in review modal

src/common/services/breathecode.js, src/pages/choose-program/index.jsx, src/pages/cohort/[cohortSlug]/[slug]/[version]/index.jsx
https://github.com/breatheco-de/breatheco-de/issues/7609
=> add pagination to me events

src/common/components/DynamicContentCard/FeatureIndicator.jsx
https://github.com/breatheco-de/breatheco-de/issues/7613
=> Fix icons in assets cards

src/common/components/ReviewModal/FileList.jsx
https://github.com/breatheco-de/breatheco-de/issues/7635
=> Fix coderevision file list

public/locales/en/choose-program.json, public/locales/es/choose-program.json, src/pages/choose-program/index.jsx
https://github.com/breatheco-de/breatheco-de/issues/7413
=> change slack community link by whats app community link

src/common/components/SupportSidebar/MentoringConsumables.jsx, src/common/components/UpgradeForConsumableView.jsx, src/common/handlers/subscriptions.js, src/js_modules/checkout/SelectServicePlan.jsx
https://github.com/breatheco-de/breatheco-de/issues/7619
=> Fix planoffer when upgrading plan

src/pages/docs/[syllabusSlug]/[assetSlug]/index.jsx, src/pages/docs/[syllabusSlug]/index.jsx
https://github.com/breatheco-de/breatheco-de/issues/7703
=> Fix prev and next article on docs pages

public/locales/en/signup.json, public/locales/es/signup.json, src/pages/checkout/index.jsx
https://github.com/breatheco-de/breatheco-de/issues/7455
=> Show self applied coupon slug on special offer

src/common/components/Forms/Signup.jsx
=> Revert "Update Signup.jsx"

src/js_modules/checkout/PaymentInfo.jsx
issue: https://github.com/breatheco-de/breatheco-de/issues/7618
=> :recycle: refactor of the code to {paymentMethod.length === 1 && [0]} in line 357

src/common/components/Footer.jsx
issue: https://github.com/breatheco-de/breatheco-de/issues/7672
=> :recycle: When user is logged, Footer component will return a Container with a margin top of 3 rem

src/common/components/Forms/Signup.jsx, src/common/components/MktRecommendedCourses.jsx, src/common/components/ShowOnSignup.jsx, src/js_modules/checkout/ContactInformation.jsx
https://github.com/breatheco-de/breatheco-de/issues/7729
=> Make extraFields support array of objects and validations

scripts/prepare-asset-data.js, src/pages/how-to/[slug]/index.jsx, src/pages/interactive-coding-tutorial/[slug].jsx, src/pages/interactive-exercise/[slug]/index.jsx, src/pages/lesson/[slug].jsx
https://github.com/breatheco-de/breatheco-de/issues/7745
=> extract readme from asset-list.json and remove vercel cache

public/locales/en/footer.json, src/common/components/Footer.jsx, src/common/components/FooterTC.jsx
=> :recycle: added FooterTC (terms and conditions) as a footer when user is auth and as a div when user is not

public/locales/en/exercises.json, public/locales/es/exercises.json, src/common/components/Instructors.jsx
fix: open with learnpack in uppercase and order instructors by role in intructors component
=> Fix two issues

src/common/components/AttendanceModal/index.jsx, src/common/components/LiveEvent/index.jsx, src/pages/cohort/[cohortSlug]/[slug]/[version]/index.jsx
Issue: [Issue #7639](https://github.com/breatheco-de/breatheco-de/issues/7639)
Description:
The issue was caused by the syncInterval function located in choose-program/index.jsx. This function was forcing the chooseProgram component to re-render every 60 seconds to keep users updated with new live events.
Initially, I attempted to prevent unnecessary re-renders by checking for new live events before re-rendering the component. However, this approach proved less effective as it still required a reset of the component when needed.
During the fix, I identified two minor bugs:
1. Default Day Issue: The default day in the attendanceModal is not functioning correctly; it always resets to 0.
2. Responsive Design Issue: When navigating to cohort/[cohortslug]/[slug]/[version] on a laptop (screen …
=> :bug: when editting attendance user will not experience a reset of the attendance after 30-50seconds

src/common/components/FooterTC.jsx
=> 💄 footer is not visible during the guided experience

src/pages/cohort/[cohortSlug]/[slug]/[version]/index.jsx, src/pages/pricing.jsx
I feel that all the queries are correctly implemented in the frontend code, and if there were any issues with the queries, the `catch` blocks would redirect the user to other pages.
The error hasn't occurred again in production, but since it happens occasionally and the data loads correctly when the page is refreshed, I suspect it might be due to some promises resolving in different orders (due to network conditions), which is why tasks are not rendered correctly in some cases.
I made some changes to the code that should ensure certain conditions are completed before others are executed.
It's possible that when the user first arrives at the page, not all the data for `cohortProgram` or `taskTodo` is ready, and that’s why tasks are not rendered. However, when the page is refreshed, the …
=> :bug: attempt to fix bug related to tasks not loading after user buys a program

public/locales/en/syllabus.json, public/locales/es/syllabus.json, src/pages/syllabus/[cohortSlug]/[lesson]/[lessonSlug]/index.jsx
=> :globe_with_meridians: add traslation to hardcoded Link

src/common/components/MktSideRecommendations.jsx, src/pages/lesson/[slug].jsx
=> :recycle: changes in the code related to colors, padding, margin

src/common/components/CodeViewer.jsx, src/common/components/DynamicContentCard/index.jsx, src/common/components/RelatedContent.jsx, src/js_modules/navbar/MobileNav.jsx, src/js_modules/projects/ProjectList.jsx, src/pages/lesson/[slug].jsx, src/pages/lessons/index.jsx, src/utils/requests.js
https://github.com/breatheco-de/breatheco-de/issues/7801
https://github.com/breatheco-de/breatheco-de/issues/7798
https://github.com/breatheco-de/breatheco-de/issues/7550
=> fix issue with related assets

public/locales/en/syllabus.json, public/locales/es/syllabus.json, src/common/components/MarkDownParser/index.jsx, src/js_modules/syllabus/ExerciseGuidedExperience.jsx, src/js_modules/syllabus/ModalToCloneProject.jsx, src/js_modules/syllabus/OpenWithLearnpackCTA.jsx, src/js_modules/syllabus/ProjectBoardGuidedExperience.jsx, src/js_modules/syllabus/TaskCodeRevisions.jsx, src/pages/syllabus/[cohortSlug]/[lesson]/[lessonSlug]/index.jsx
https://github.com/breatheco-de/breatheco-de/issues/7648
https://github.com/breatheco-de/breatheco-de/issues/7812
=> Fix details in Guided experience

src/js_modules/checkout/PaymentInfo.jsx, src/js_modules/checkout/Summary.jsx
=> ⚡ user is added inmedialy to the cohort when paymen is successful

src/common/components/CodeViewer.jsx, src/common/components/MarkDownParser/index.jsx
tests made with: `es/lesson/fake-tomas-code-viewer`
=> ♻️ codedViewer and markdown edited to accept node and node.js

src/pages/checkout/index.jsx
=> :bug: fix of NaN

src/pages/how-to/[slug]/index.jsx
=> ✨ added table of content in how-to

src/common/components/SupportSidebar/MentoringConsumables.jsx
When looking for mentorship/schedule it will show first a skeleton as loading cards
=> 💄 adding skeleton in mentorship/schedule

src/js_modules/syllabus/OpenWithLearnpackCTA.jsx
https://github.com/breatheco-de/breatheco-de/issues/7867
=> disable vendor comprobation on learnpack cta

src/js_modules/syllabus/TimelineSidebar.jsx, src/pages/syllabus/[cohortSlug]/[lesson]/[lessonSlug]/index.jsx
https://github.com/breatheco-de/breatheco-de/issues/7863
=> Add no instructions warning message

src/common/components/ReviewModal/CodeReview.jsx, src/common/components/ReviewModal/index.jsx
=> 🐛 fix when selecting another code review

src/common/components/Timeline.jsx, src/js_modules/moduleMap/index.jsx, src/js_modules/syllabus/GuidedExperienceSidebar.jsx, src/utils/index.js
=> ✨ adding traslation to title and desc of modules

src/common/components/ReviewModal/CodeReview.jsx
=> increse size of code review

src/pages/syllabus/[cohortSlug]/[lesson]/[lessonSlug]/index.jsx
https://github.com/breatheco-de/breatheco-de/issues/7713
=> Fix send project button

src/common/components/Forms/Signup.jsx
https://github.com/breatheco-de/breatheco-de/issues/7887
=> Add marketing consent to sbscription request

src/pages/cohort/[cohortSlug]/student/[studentId]/index.jsx
https://github.com/breatheco-de/breatheco-de/issues/7627
=> Fix status bug

public/locales/en/syllabus.json, public/locales/es/syllabus.json, public/no-learnpack-in-cloud.json, src/js_modules/projects/TabletWithForm.jsx, src/js_modules/syllabus/ExerciseGuidedExperience.jsx, src/js_modules/syllabus/OpenWithLearnpackCTA.jsx, src/js_modules/syllabus/ProjectBoardGuidedExperience.jsx, src/pages/syllabus/[cohortSlug]/[lesson]/[lessonSlug]/index.jsx
=> ✨ adding built learnpackurl

src/js_modules/syllabus/GuidedExperienceSidebar.jsx
=> :bug: fix in text wrapping

public/locales/en/common.json, public/locales/es/common.json, src/js_modules/projects/TabletWithForm.jsx, src/js_modules/syllabus/OpenWithLearnpackCTA.jsx
=> traslation

public/locales/en/common.json, public/locales/es/common.json, src/common/components/Timer.jsx
=> changes in time

public/locales/en/footer.json, public/locales/es/footer.json, src/common/components/Footer.jsx, styles/globals.css
https://github.com/breatheco-de/breatheco-de/issues/7912
=> Hide google recaptcha badge

src/js_modules/syllabus/ExerciseGuidedExperience.jsx, src/pages/syllabus/[cohortSlug]/[lesson]/[lessonSlug]/index.jsx
=> ✨ remove buttons when starting exercises and projects

public/locales/en/dashboard.json, public/locales/es/dashboard.json, src/common/components/PopoverTaskHandler.jsx, src/js_modules/moduleMap/ButtonHandlerByTaskStatus.jsx
=> ✨ adding T&C to project deliver

src/js_modules/syllabus/OpenWithLearnpackCTA.jsx
=> :ambulance: hotfix

src/common/components/PopoverTaskHandler.jsx
=> :recycle: clicktext to check the box

public/locales/en/common.json, public/locales/es/common.json, src/js_modules/syllabus/OpenWithLearnpackCTA.jsx
=> ♻️ details to button

src/js_modules/projects/TabletWithForm.jsx, src/js_modules/syllabus/OpenWithLearnpackCTA.jsx
=> ❇️ adding external in CTA

src/js_modules/projects/TabletWithForm.jsx
=> uppercase added to button

src/pages/syllabus/[cohortSlug]/[lesson]/[lessonSlug]/index.jsx
=> ❇️ close guided expertience when starting interactive exercise

public/locales/en/signup.json, src/pages/bootcamp/[course_slug].jsx
=> change in text

src/common/views/FinalProjects.jsx
=> small change

public/locales/en/code-viewer.json, public/locales/es/code-viewer.json, src/common/components/CodeViewer.jsx
https://github.com/breatheco-de/breatheco-de/issues/7985
=> Agregar funcionalidad de preview para lenguajes html, css y vanillajs

package.json, public/locales/en/signup.json, public/locales/en/syllabus.json, public/locales/es/signup.json, public/locales/es/syllabus.json, src/common/context/RigoContext.jsx, src/pages/syllabus/[cohortSlug]/[lesson]/[lessonSlug]/completion-jobs.json, src/pages/syllabus/[cohortSlug]/[lesson]/[lessonSlug]/index.jsx
https://github.com/breatheco-de/breatheco-de/issues/7984
=> Personalize Rigobot greeting message for lessons

src/common/store/actions/signupAction.js
=> silent error

src/common/components/MktSideRecommendations.jsx
=> ♻️  add color to button in mktsideRecom

src/common/components/Timeline.jsx, src/js_modules/syllabus/GuidedExperienceSidebar.jsx, src/pages/syllabus/[cohortSlug]/[lesson]/[lessonSlug]/index.jsx
=> 💄 fix in design

src/common/components/MarkDownParser/MDComponents/index.jsx, src/common/components/OnlyFor.jsx
**test asset title**: What is HTML? It's time to learn HTML and its structure
**test asset slug**: what-is-html-learn-html
**no-saas-cohort**:  miami-40
**saas-cohort**:  4geeks-fs-1
expected behavior:
=> ♻️ allow saas and withbanner props

src/js_modules/checkout/CardForm.jsx, src/js_modules/checkout/PaymentInfo.jsx
=> 🐛  fix when comming back from try again

src/common/components/MktSideRecommendations.jsx
=> ♻️ improve algorithm to show course

scripts/redirects-generator.js, src/pages/syllabus/[cohortSlug]/[lesson]/[lessonSlug]/index.jsx
=> 🐛 small fix

src/common/components/Navbar/index.jsx, src/pages/cohort/[cohortSlug]/[slug]/[version]/index.jsx, src/pages/syllabus/[cohortSlug]/[lesson]/[lessonSlug]/index.jsx
=> ♻️ send users to the checkout after alert

src/js_modules/syllabus/ProjectInstructions.jsx, src/pages/syllabus/[cohortSlug]/[lesson]/[lessonSlug]/index.jsx
=> 🐛 fix on start interactive <asset>

src/common/components/MarkDownParser/MDComponents/index.jsx
=> using version 1 of quotes

src/common/components/MarkDownParser/MDComponents/index.jsx, src/middleware.js
=> refactor middleware for redirects

public/locales/en/dashboard.json, public/locales/es/dashboard.json
=> small change on traslation

src/pages/syllabus/[cohortSlug]/[lesson]/[lessonSlug]/index.jsx
=> change algorithm to find currentTask

public/locales/en/common.json, public/locales/es/common.json, src/common/services/breathecode.js, src/js_modules/syllabus/ExerciseGuidedExperience.jsx, src/js_modules/syllabus/ProjectInstructions.jsx, src/pages/syllabus/[cohortSlug]/[lesson]/[lessonSlug]/index.jsx
=> small refactor

src/common/handlers/cohorts.js, src/common/services/breathecode.js
=> ♻️ include correct version on ep

src/js_modules/syllabus/ProjectBoardGuidedExperience.jsx, src/js_modules/syllabus/ProjectInstructions.jsx
=> ♻️ refactor to include extra-small

package-lock.json, src/common/components/FilterModal/index.jsx, src/pages/how-to/index.jsx, src/pages/interactive-coding-tutorials/index.jsx, src/pages/interactive-exercises/index.jsx, src/pages/lessons/index.jsx
https://github.com/breatheco-de/breatheco-de/issues/8225
https://github.com/breatheco-de/breatheco-de/issues/8226
=> Only show technologies with priority higher than 2 in the filter modal

package-lock.json, src/pages/bootcamp/[course_slug].jsx
https://github.com/breatheco-de/breatheco-de/issues/8151
=> add coupons to context rigobot

src/js_modules/syllabus/ProjectInstructions.jsx
=> small change in button

package-lock.json, src/common/components/MktRecommendedCourses.jsx, src/common/components/MktSideRecommendations.jsx
=> get translation when changing lang

src/common/components/ShowPrices.jsx, src/common/store/actions/signupAction.js, src/pages/bootcamp/[course_slug].jsx
https://github.com/breatheco-de/breatheco-de/issues/8231
=> Add more coupon context to rigobot

src/js_modules/checkout/PaymentInfo.jsx, src/pages/checkout/index.jsx
=> ♻️ small change to open checkout dropdown

package-lock.json, src/pages/syllabus/[cohortSlug]/[lesson]/[lessonSlug]/index.jsx
=> ♻️ avoid asking for readme on saas

src/pages/cohort/[cohortSlug]/[slug]/[version]/index.jsx
=> 🐛 fix to scroll into last done module

src/common/handlers/index.js
=> small change to include new status

public/locales/en/common.json
=> adding videos

src/js_modules/syllabus/ExerciseGuidedExperience.jsx
https://github.com/breatheco-de/breatheco-de/issues/8264
=> Remove decimals from minutes

src/pages/cohort/[cohortSlug]/[slug]/[version]/index.jsx
https://github.com/breatheco-de/breatheco-de/issues/8283
=> fix bug not allowing user with active subscription

src/js_modules/syllabus/ProjectInstructions.jsx
=> button bigger

src/js_modules/syllabus/ProjectInstructions.jsx
=> small change when is external and no saas

src/pages/syllabus/[cohortSlug]/[lesson]/[lessonSlug]/index.jsx
=> 🐛 adding funciton to manage onlyFor and comments in ai_context

src/common/store/actions/signupAction.js
=> get the real bag id

public/locales/en/footer.json, public/locales/es/footer.json, src/common/components/FooterTC.jsx
=> adding code of conduct

src/common/components/ReactPlayerV2.jsx, src/js_modules/syllabus/ModalToCloneProject.jsx
=> ♻️ autoplay videos in modal

public/locales/en/common.json, public/locales/es/common.json, src/js_modules/syllabus/ModalToCloneProject.jsx
=> ♻️ add create folder step on template_url

src/pages/bootcamp/[course_slug].jsx
=> ♻️ small refactor to add discounts on bootcamps

public/locales/en/exercises.json, public/locales/es/exercises.json, src/js_modules/projects/TabletWithForm.jsx
=> small change in title

prismicio-types.d.ts, slices/MultipleColumnCard/mocks.json, slices/MultipleColumnCard/model.json, src/common/components/MktMultipleColumnCard.jsx
- It is not published yet in Prismic
=> Create the how it works component

src/common/components/MktMultipleColumnCard.jsx
=> Add width and update gap

src/common/components/MktMultipleColumnCard.jsx
Add property width 100% in image
=> Add width 100% in image

src/pages/bootcamp/[course_slug].jsx
=> Faq is taking less width than it should

public/locales/en/live-event.json, public/locales/es/live-event.json, src/common/components/DynamicContentCard/index.jsx
=> adding event details

src/common/components/MktPricingCards.jsx
=> Add title in pricing cards

src/pages/[uid]/index.jsx
=> Add background

public/locales/en/syllabus.json, public/locales/es/syllabus.json, src/common/components/MarkDownParser/ArticleMarkdown.jsx, src/pages/lessons/index.jsx, src/pages/syllabus/[cohortSlug]/[lesson]/[lessonSlug]/index.jsx
=> fix conditional to avoid bug

src/pages/bootcamp/[course_slug].jsx, src/pages/checkout/index.jsx, src/pages/pricing.jsx
- im not sure if this is caused by the back aswell but im seeing that one payment option got separated from financing options on pricing view
=> apply discounts to title before cardInfo step

public/sitemap.xml, src/utils/requests.js
=> ♻️ getting prismic pages in sitmaps

src/pages/bootcamp/[course_slug].jsx
=> bug on text in the button

src/common/components/CodeViewer.jsx
=> 🐛 do not let macos run in codeviewer

public/locales/en/common.json, public/locales/es/common.json, src/common/components/MktSideRecommendations.jsx
https://github.com/breatheco-de/breatheco-de/issues/8411
=> redesign small marketing call to action

src/pages/api/asset/[assetSlug].js, src/pages/api/cache/[slug]/index.js, src/pages/api/cache/index.js, src/pages/how-to/[slug]/index.jsx, src/pages/interactive-coding-tutorial/[slug].jsx, src/pages/interactive-exercise/[slug]/index.jsx, src/pages/lesson/[slug].jsx, src/utils/requests.js
https://github.com/breatheco-de/breatheco-de/issues/8465
=> Reuse function to query the markdowns in the cache

src/common/components/Navbar/index.jsx, src/pages/bootcamp/[course_slug].jsx
=> ✨ adding new feature to get started button when in bootcamp

src/common/components/MktTwoColumnSideImage.jsx, src/common/components/ReactPlayerV2.jsx
=> small changes to avoid bug on movile

public/locales/en/common.json, public/locales/es/common.json, src/common/components/Icon/set/shield.jsx, src/common/components/ShowPrices.jsx, src/pages/bootcamp/[course_slug].jsx
=> ✨ adding money back guarantee on buttons

src/common/components/MktTwoColumnSideImage.jsx, src/common/components/ReactPlayerV2.jsx
=> fix bug of dissappearing in mobile

src/js_modules/projects/FixedBottomCta.jsx
=> :bug: small fix

src/common/components/MktSideRecommendations.jsx
https://github.com/breatheco-de/breatheco-de/issues/8411
=> Nueva version del componente de call to action

src/common/components/LanguageSelector.jsx, src/common/components/Navbar/index.jsx
the navbar was not cleaning the data on each render causing the duplication
=> 🐛  fix with duplicates in json

src/pages/bootcamp/[course_slug].jsx
=> adding reading ex, etc

public/locales/es/syllabus.json, src/pages/syllabus/[cohortSlug]/[lesson]/[lessonSlug]/index.jsx
=> ♻️ avoid requesting asset when lesson is blank

src/js_modules/profile/Subscriptions/index.jsx
=> ♻️ small changes in subscription cards

src/utils/requests.js
=> ♻️ only generate sitemaps for is_listed = true courses

src/common/components/DynamicContentCard/HeadInfo.jsx, src/common/components/DynamicContentCard/index.jsx, src/common/components/MktEventCards.jsx, src/common/components/WorkshopsLoggedLanding.jsx
=> change on eventcard

src/common/components/KPI.jsx, src/js_modules/syllabus/ExerciseGuidedExperience.jsx
=> ♻️ changes in grid of exercisesGuidedExp

src/common/components/ShowPrices.jsx
=> changes requested

src/common/components/Forms/LogIn.jsx, src/js_modules/profile/Subscriptions/index.jsx
=> submit in login divided in two steps

src/common/components/MarkDownParser/MDComponents/index.jsx
=> 🐛 fix ObjectObject bug on Code parser

public/locales/en/course.json, public/locales/es/course.json, src/common/components/Icon/set/shield.jsx, src/pages/bootcamp/[course_slug].jsx
=> vibe codign students imagens and button with course color

src/pages/index.jsx
=> ✨ moving user to es homepage if preffered language is es

public/locales/en/common.json, public/locales/es/common.json
=> adding videos on open with template instructions

src/js_modules/moduleMap/index.jsx
=> start modeule takes you to first lesson

src/common/components/ReactPlayerV2.jsx, src/common/hooks/useCohortHandler.js, src/pages/bootcamp/[course_slug].jsx
=> changes to the reactplayer

src/utils/regex.js
=> less restrictive email (maintaining domain restrictions)

public/locales/en/program-card.json, public/locales/es/program-card.json, src/common/components/ProgramCard.jsx
=> adding see more see less after 4 MKTbullets

src/pages/checkout/index.jsx
=> solve bug of already applied coupon

src/common/components/ReactPlayerV2.jsx
The implementation included in the GPT chat is already applied, however i include in this pr some performance adjustments
=> changes in improvement

modifyTheme.js, src/pages/_app.jsx
1. Se creó un nuevo archivo `modifyTheme.js` que maneja la lógica del tema con el siguiente orden de prioridad:
```javascript
const handleTheme = () => {
// 1. Primero verifica el querystring theme
const urlTheme = new URLSearchParams(window.location.search).get('theme');
// 2. Luego verifica el tema guardado en localStorage
const storedTheme = localStorage.getItem('chakra-ui-color-mode');
// 3. Finalmente verifica las preferencias del sistema
const prefersDark = window.matchMedia('(prefers-color-scheme: dark)').matches;
}
```
2. Se modificó `_app.jsx` para inicializar el tema solo cuando:
- Es la primera visita (no hay tema guardado)
- Hay un parámetro `theme` en la URL
1. **Querystring `?theme=dark` o `?theme=light`**:
- Si se incluye en la URL, fuerza ese tema específico
- Ejemplo: …
=> ✨ allowing ?theme=dark query string and use preference of user

src/common/components/ProgressCircle/index.jsx, src/js_modules/syllabus/SubtasksPill.jsx, src/js_modules/syllabus/Topbar.jsx
=> 🐛  small change to pills on top bar

src/pages/choose-program/index.jsx
https://github.com/breatheco-de/breatheco-de/issues/7592
=> Fix bug with infinite loagin on cohorts

src/components/CohortPanel.jsx
=> use play button when module not started

src/components/SupportSidebar/MentoringConsumables.jsx, src/pages/mentorship/schedule.jsx
https://github.com/breatheco-de/breatheco-de/issues/8755
=> Add two lines description to mentoring conmonent

public/locales/en/dashboard.json, public/locales/es/dashboard.json, src/components/MarkDownParser/index.jsx, src/components/SupportSidebar/MentoringConsumables.jsx, src/hooks/useCohortHandler.js, src/pages/cohort/[cohortSlug]/[slug]/[version]/index.jsx
=> changes in dashboard continue button + profiles + name and description

src/components/MktEventCards.jsx
=> change past events when chhanging lang

src/components/CohortHeader.jsx, src/pages/cohort/[cohortSlug]/[slug]/[version]/index.jsx
=> adding the modal for connect to githuv

src/pages/bootcamp/[course_slug].jsx
=> >20 students to show them

src/pages/bootcamp/[course_slug].jsx
=> adding preview

src/hooks/useCustomToast.jsx, src/pages/cohort/[cohortSlug]/[slug]/[version]/index.jsx
=> 🐛 when clicking on a button of a toast it should close

public/locales/en/alert-message.json, public/locales/es/alert-message.json, src/hooks/useCohortHandler.js, src/pages/choose-program/index.jsx, src/pages/cohort/[cohortSlug]/[slug]/[version]/index.jsx
https://github.com/breatheco-de/breatheco-de/issues/8413
=> Show alert to students with finantial_status late

public/locales/en/syllabus.json, public/locales/es/syllabus.json, src/pages/syllabus/[cohortSlug]/[lesson]/[lessonSlug]/index.jsx
=> 🐛  fix on toast (ojbect object)

src/components/CohortPanel.jsx, src/pages/cohort/[cohortSlug]/[slug]/[version]/index.jsx
=> ♻️  refactor of cohortPanel component

src/components/MktEventCards.jsx
=> adding current, future and, past events

src/components/GuidedExperience/SyllabusMarkdownComponent.jsx, src/components/MarkDownParser/ArticleMarkdown.jsx, src/pages/syllabus/[cohortSlug]/[lesson]/[lessonSlug]/index.jsx
=> 🐛  adding message for teachers

src/pages/bootcamp/[course_slug].jsx
=> 🐛  small change to prio proyects to fill

src/components/Navbar/index.jsx, src/pages/pricing.jsx
https://github.com/breatheco-de/breatheco-de/issues/8856
=> Country code

src/components/AlertMessage.jsx, src/components/IntroductionSection.jsx, src/components/MktAwardsSection.jsx, src/components/MktMultipleColumnCard/index.jsx, src/components/MktOneColumnSection/index.jsx, src/components/MktSplitShowcaseSection.jsx, src/components/MktTwoColumnSideImage.jsx, src/components/PrismicTextComponent.jsx, src/components/ProgramsDashboard/index.jsx, src/components/ReactPlayerV2.jsx, src/components/ReviewModal/CodeReview.jsx, src/pages/index.jsx
=> refactoring of reactVideoV2 and home changes

src/components/TaskBar.jsx
related to the icon on the events sidebar. it is a picture comming from google storage.
=> 💄 color change on modules numbers background to bluedefault

src/components/MktOneColumnSection/ImageOnTopVariation.jsx, src/pages/bootcamp/[course_slug].jsx
=> 💄 changes on oneColumnImage

src/components/Navbar/index.jsx
=> allow aprender on for spaniars

src/pages/bootcamp/useBootcamp.js
=> 🐛 infinite scroll when joinin cohort

public/locales/en/workshops.json, public/locales/es/workshops.json, src/components/PrismicComponents/MktEventCards.jsx, src/components/WorkshopsLoggedLanding.jsx
=> adding past events to workshops logged landing

src/components/Navbar/MobileNav.jsx, src/components/Navbar/index.jsx
=> ✨ apply overlay when navbar is open

src/pages/checkout/index.jsx, src/pages/checkout/useCheckout.js, src/pages/how-to/technology/[technology].jsx
Bug 1:  When user types a coupon and hit add it loads forever
Bug 2: When removing the coupon it reapplies itself and we have to click again the x button
=> 🐛  infinite loading on coupons

src/middleware.js, src/pages/how-to/technology/[technology].jsx, src/pages/interactive-exercises/technology/[technology].jsx, src/pages/lessons/technology/[technology].jsx
=> 🐛 static redirections working

src/pages/bootcamp/useBootcamp.js
=> 🐛  when loading proyects filter by lang

src/middleware.js
=> 🐛  middleware not working when adding querystrings

src/hooks/useAddToCalendar.js, src/pages/workshops/[event_slug].jsx
=> 🐛 bugs when refreshing the page and changes requested

.cursor/rules/components.mdc, public/locales/en/alert-message.json, public/locales/en/dashboard.json, public/locales/es/alert-message.json, public/locales/es/dashboard.json, src/components/AssignmentButton/DeliveryFormat.jsx, src/components/AssignmentButton/FileDeliveryFormat.jsx, src/components/AssignmentButton/FlagsDeliveryFormat.jsx, src/components/AssignmentButton/NoDeliveryFormat.jsx, src/components/AssignmentButton/ProjectSubmitButton.jsx, src/components/AssignmentButton/UrlDeliveryFormat.jsx, src/components/MarkDownParser/MDComponents/index.jsx, src/hooks/useCohortHandler.js, src/pages/syllabus/[cohortSlug]/[lesson]/[lessonSlug]/index.jsx, src/services/breathecode.js
=> ♻️ ✨ code refactoring for future formats and new format CTF included

public/locales/en/projects.json, public/locales/es/projects.json, src/hooks/useCohortHandler.js, src/pages/syllabus/[cohortSlug]/[lesson]/[lessonSlug]/index.jsx
=> 🐛 remove innecesary toast and change modal text when delivering a project

src/components/AssignmentButton/FileDeliveryFormat.jsx, src/components/AssignmentButton/FlagsDeliveryFormat.jsx, src/components/AssignmentButton/NoDeliveryFormat.jsx, src/components/AssignmentButton/UrlDeliveryFormat.jsx, src/components/GuidedExperience/ProjectBoardGuidedExperience.jsx, src/hooks/useCohortHandler.js, src/pages/syllabus/[cohortSlug]/[lesson]/[lessonSlug]/index.jsx, src/services/breathecode.js
=> 🐛 users get quick response about project delivering

src/components/CohortHeader.jsx, src/pages/cohort/[cohortSlug]/[slug]/[version]/index.jsx
1. Go to the admin and get into the main cohort you want to test the issue.
2. on that cohort get into the shortcuts variable and add the variables (specified on the issue description). The following picture is from `vibe-coding-with-ai` course
3. take into consideration that the variables allowed by the frontend are: label, help_text, help_text_link, icon (is a string of one of the icons that we have already on the app eg. bootstrap), icon_url, icon_url_alternative_text
When configuring correctly the cohort get into a saas cohort and you should be able to see a new widget added (shown in the following picture)
=> ✨  adding shortcuts to the dashboard header from cohort variable

public/locales/en/course.json, public/locales/es/course.json, src/components/PageBubble.jsx, src/pages/bootcamp/[course_slug].jsx, src/pages/bootcamp/useBootcamp.js
This pull request introduces a key feature: the display of a new and improved responsive WhatsApp contact bubble. The goal is to provide a more comprehensive and visually appealing user experience on desktop screens while maintaining a compact and familiar view on mobile devices.
* **Responsive View Logic in `PageBubble`**:
* The `PageBubble` component has been refactored to use the `useBreakpointValue` hook, allowing it to select the appropriate content and styles (`base` for mobile or `md` for desktop) based on the screen size.
* The `content` prop is now an object containing the content for both views (`base` and `md`), enabling `PageBubble` to handle the presentation logic autonomously.
* **Integration with `landing_variables`**:
* The bubble's content configuration has been …
=> Feature: Implementation of Responsive WhatsApp Bubble for Desktop.

src/components/AssignmentButton/FlagsDeliveryFormat.jsx, src/components/ReviewModal/AssignmentReview.jsx
=> :recycle: changes on translations

src/components/CohortHeader.jsx
=> changes to the shortcuts to accept lang switch

src/pages/syllabus/[cohortSlug]/[lesson]/[lessonSlug]/index.jsx
=> allow contributions

src/pages/workshops/[event_slug].jsx
=> revalidate

src/pages/bootcamp/useBootcamp.js
=> 🐛 adding fully paid to related sub

src/utils/index.js
=> small change to langFix to accept falsy values

public/locales/en/profile.json, public/locales/es/profile.json, src/components/Profile/Subscriptions/handlers.jsx, src/pages/pricing.jsx
=> changes applied to text on subscription card

src/components/GuidedExperience/ProjectBoardGuidedExperience.jsx
=> small change to center text

src/components/PrismicComponents/MktHeroSection.jsx
=> cta of bootcamcp appears first

src/components/CohortPanel.jsx, src/components/GuidedExperience/ExerciseGuidedExperience.jsx, src/components/Timeline.jsx, src/pages/syllabus/[cohortSlug]/[lesson]/[lessonSlug]/index.jsx
=> changes to improve cohort dashboard and guided experience

src/pages/mentorship/schedule.jsx, src/pages/syllabus/[cohortSlug]/[lesson]/[lessonSlug]/index.jsx
=> 🐛 error 404 on quiz

src/components/Forms/Signup.jsx
Issue: https://github.com/breatheco-de/breatheco-de/issues/9752
=> Fix on missing prop for PhoneInput component

src/components/CohortPanel.jsx
=> 🐛  correct bug with pending revisions

src/pages/lesson/[slug].jsx
=> fiexs to main

src/pages/lesson/[slug].jsx
=> solving problems on main with rendering static pages

src/components/PrismicComponents/MktAwardsSection.jsx
Issue: https://github.com/breatheco-de/breatheco-de/issues/9750
=> Change to default size of awards images

src/components/ProgramCard.jsx, src/components/ProgramsDashboard/Program.jsx, src/components/ProgramsDashboard/index.jsx, src/pages/pricing.jsx
Issue: https://github.com/breatheco-de/breatheco-de/issues/9853
Now it looks like this. I added extra props to the ProgramCard components to control de background and reverted the colours here, since the page background was already blue
=> Replaced CourseCard with ProgramCard in self-paced courses pricing
